// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"log/slog"
	"myapp/app"
	"myapp/app/bus"
	"myapp/app/bus/bus_middleware"
	"myapp/app/config"
	"myapp/app/console"
	"myapp/app/database"
	"myapp/app/domain/shared"
	"myapp/app/http/handler"
	"myapp/app/http/server"
)

// Injectors from container_provider.go:

func CreateApplication(logger *slog.Logger) (*app.Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	serverServer := server.NewServer(configConfig, logger, healthHandler)
	serveCommand := console.NewServeCommand(serverServer)
	rootCommand := console.NewRootCommand(serveCommand)
	sqliteManager, err := database.NewSqliteManager(configConfig)
	if err != nil {
		return nil, err
	}
	migrationManager := database.NewMigrationManager(sqliteManager, logger)
	application := app.NewApplication(rootCommand, migrationManager)
	return application, nil
}

// container_provider.go:

func provideEventCollector() *shared.EventCollector {
	return shared.NewEventCollector()
}

func provideCommandBus(logger *slog.Logger, db *database.SqliteManager, collector *shared.EventCollector) *bus.CommandBus {
	return &bus.CommandBus{Bus: bus.New(bus_middleware.RecoveryMiddleware(logger), bus_middleware.LoggingMiddleware(logger), bus_middleware.TransactionMiddleware(db), bus_middleware.DispatchEventsMiddleware(logger, collector))}
}

func provideQueryBus(logger *slog.Logger) *bus.QueryBus {
	return &bus.QueryBus{Bus: bus.New(bus_middleware.RecoveryMiddleware(logger), bus_middleware.LoggingMiddleware(logger))}
}

func provideEventBus(logger *slog.Logger) *bus.EventBus {
	return &bus.EventBus{Bus: bus.New(bus_middleware.RecoveryMiddleware(logger), bus_middleware.LoggingMiddleware(logger))}
}
