// Command tsgen generates TypeScript type definitions from annotated Go structs,
// so the frontend request/response types can never silently drift from the Go
// DTOs that actually cross the HTTP wire (audit finding F-082).
//
// A Go struct opts in with a directive comment naming the TS type and its exact
// output path (the author places each type precisely where the frontend needs
// it):
//
//	//gkts:LoginResponse assets/app-ui/Auth/types/LoginResponse.ts
//	type loginResponse struct { ... }
//
// tsgen maps the struct's json-tagged fields to TS and writes (or, in `check`
// mode, verifies) the target file. It is a separate module (own go.mod) so the
// project linters — which forbid stdout and direct file writes — do not apply to
// a tool whose whole job is exactly that.
//
// Type mapping is deliberately SMALL and fail-loud: it maps only the Go types the
// DTOs actually use and ERRORS on anything else, rather than emitting `any` and
// re-opening the very parity gap it exists to close. Extend mapType when a new
// field type appears; never let it guess.
//
// Usage:
//
//	tsgen generate   # write the TS files (make ts-gen)
//	tsgen check      # verify on-disk files match; exit 1 on drift (CI gate)
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

const genHeader = "// Code generated by tsgen; DO NOT EDIT."

// directive is a parsed //gkts:<Name> <path> annotation.
type directive struct {
	tsName string // TypeScript type name to emit
	tsPath string // output path, repo-relative (e.g. assets/app-ui/Auth/types/LoginResponse.ts)
}

// dtoField is one rendered field: its JSON key, TS type, optionality, and (if the
// type is another generated type) the import that type needs.
type dtoField struct {
	name     string // JSON key (= TS property name)
	tsType   string // rendered TS type
	optional bool   // json ",omitempty" → name?: type
	dep      string // Go type name of a referenced generated type, or ""
}

// dto is one annotated struct resolved to its TS shape.
type dto struct {
	goName string
	dir    directive
	fields []dtoField
}

func main() {
	mode := "generate"
	if len(os.Args) > 1 {
		mode = os.Args[1]
	}
	root := repoRoot()

	dtos, err := collect(filepath.Join(root, "app"))
	if err != nil {
		fatal("collect: %v", err)
	}
	if len(dtos) == 0 {
		fatal("no //gkts: directives found under app/ — nothing to generate")
	}

	// Index by Go type name so a nested field (e.g. userDTO) resolves to the TS
	// name + import path of the type it maps to.
	byGo := make(map[string]directive, len(dtos))
	for _, d := range dtos {
		if prev, ok := byGo[d.goName]; ok && prev != d.dir {
			fatal("Go type %q carries two conflicting //gkts: directives", d.goName)
		}
		byGo[d.goName] = d.dir
	}

	files, err := render(dtos, byGo)
	if err != nil {
		fatal("render: %v", err)
	}

	switch mode {
	case "generate":
		writeFiles(root, files)
	case "check":
		checkFiles(root, files)
	default:
		fatal("unknown mode %q (want: generate | check)", mode)
	}
}

// collect parses every non-test .go file under dir and returns the annotated DTOs.
func collect(dir string) ([]dto, error) {
	var dtos []dto
	fset := token.NewFileSet()
	err := filepath.WalkDir(dir, func(path string, e os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if e.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, perr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if perr != nil {
			return fmt.Errorf("parse %s: %w", path, perr)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				// The directive sits on the type's own doc, or (for a single-spec
				// `type X struct`) on the GenDecl's doc.
				dir, ok := parseDirective(ts.Doc, gd.Doc)
				if !ok {
					continue
				}
				fields, ferr := structFields(st)
				if ferr != nil {
					return fmt.Errorf("%s: type %s: %w", path, ts.Name.Name, ferr)
				}
				dtos = append(dtos, dto{goName: ts.Name.Name, dir: dir, fields: fields})
			}
		}
		return nil
	})
	return dtos, err
}

// parseDirective looks for a //gkts:<Name> <path> line in the given comment groups.
func parseDirective(groups ...*ast.CommentGroup) (directive, bool) {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			rest, ok := strings.CutPrefix(line, "gkts:")
			if !ok {
				continue
			}
			f := strings.Fields(rest)
			if len(f) != 2 {
				fatal("malformed directive %q (want: //gkts:<TSName> <path>)", c.Text)
			}
			return directive{tsName: f[0], tsPath: f[1]}, true
		}
	}
	return directive{}, false
}

// structFields resolves each json-serialized field to its TS shape. It errors on
// any Go field type mapType does not understand — fail loud, never emit `any`.
func structFields(st *ast.StructType) ([]dtoField, error) {
	var out []dtoField
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			return nil, fmt.Errorf("embedded fields are not supported")
		}
		name, omitempty, skip := jsonName(f)
		if skip {
			continue
		}
		for _, n := range f.Names {
			// encoding/json serializes ONLY exported fields, tag or no tag — so an
			// unexported field never reaches the wire. Emitting it would make the TS
			// assert a property that never arrives; skip it exactly as json does.
			if !n.IsExported() {
				continue
			}
			key := name
			if key == "" {
				key = n.Name // encoding/json falls back to the field name
			}
			tsType, dep, err := mapType(f.Type)
			if err != nil {
				return nil, fmt.Errorf("field %s: %w", n.Name, err)
			}
			out = append(out, dtoField{name: key, tsType: tsType, optional: omitempty, dep: dep})
		}
	}
	return out, nil
}

// jsonName reads the json tag: returns the key, whether it is ,omitempty, and
// whether the field is skipped (json:"-").
func jsonName(f *ast.Field) (name string, omitempty, skip bool) {
	if f.Tag == nil {
		return "", false, false
	}
	tag := reflect.StructTag(strings.Trim(f.Tag.Value, "`"))
	j, ok := tag.Lookup("json")
	if !ok {
		return "", false, false
	}
	parts := strings.Split(j, ",")
	if parts[0] == "-" {
		return "", false, true
	}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			omitempty = true
		}
	}
	return parts[0], omitempty, false
}

// mapType turns a Go type expression into a TS type. dep is the Go type name of a
// referenced generated type (for imports), or "". It errors on anything outside
// the small set the DTOs use — extend it deliberately, don't guess.
func mapType(expr ast.Expr) (tsType, dep string, err error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", "", nil
		case "bool":
			return "boolean", "", nil
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			return "number", "", nil
		default:
			// A named local type — valid only if it is itself a generated DTO.
			// Resolution to its TS name happens in render (which has the registry);
			// here we just carry the Go name as the dependency.
			return t.Name, t.Name, nil
		}
	case *ast.ArrayType:
		// []T -> T[] (never T[]|null). A NIL Go slice marshals to JSON `null`, which
		// would break `T[]` at runtime — so DTO slice fields MUST be non-nil-
		// initialized by the handler (the gokick convention: e.g. permissions comes
		// from registry.ForRole, which starts `[]string{}`). This tool cannot enforce
		// that at compile time; keeping T[] matches the convention and the FE's use
		// (no null-guard on arrays) rather than pessimizing every slice to |null.
		elem, dep, err := mapType(t.Elt)
		if err != nil {
			return "", "", err
		}
		return elem + "[]", dep, nil
	case *ast.StarExpr:
		elem, dep, err := mapType(t.X)
		if err != nil {
			return "", "", err
		}
		return elem + " | null", dep, nil
	default:
		return "", "", fmt.Errorf(
			"unmapped Go type %T — extend tsgen.mapType (do not emit `any`)", expr)
	}
}

// render groups DTOs by output file and produces the file contents. It resolves
// each nested dependency to the TS name + import path of the type it maps to.
func render(dtos []dto, byGo map[string]directive) (map[string]string, error) {
	// Group the DTOs targeting each file, in the order encountered.
	byFile := map[string][]dto{}
	var order []string
	for _, d := range dtos {
		if _, seen := byFile[d.dir.tsPath]; !seen {
			order = append(order, d.dir.tsPath)
		}
		byFile[d.dir.tsPath] = append(byFile[d.dir.tsPath], d)
	}

	out := make(map[string]string, len(order))
	for _, path := range order {
		group, err := dedupe(path, byFile[path])
		if err != nil {
			return nil, err
		}

		// A file may host several types; a name defined here needs no import.
		localNames := map[string]bool{}
		for _, d := range group {
			localNames[d.dir.tsName] = true
		}

		imports := map[string]string{} // tsName -> import specifier
		var body strings.Builder
		for i, d := range group {
			if i > 0 {
				body.WriteString("\n")
			}
			if err := renderType(&body, d, byGo, localNames, imports); err != nil {
				return nil, fmt.Errorf("%s: %w", path, err)
			}
		}

		var sb strings.Builder
		sb.WriteString(genHeader + "\n")
		if len(imports) > 0 {
			sb.WriteString("\n")
			names := make([]string, 0, len(imports))
			for n := range imports {
				names = append(names, n)
			}
			sort.Strings(names)
			for _, n := range names {
				fmt.Fprintf(&sb, "import type { %s } from '%s';\n", n, imports[n])
			}
		}
		sb.WriteString("\n")
		sb.WriteString(body.String())
		out[path] = sb.String()
	}
	return out, nil
}

// dedupe collapses DTOs that map to the same TS name in one file. Several Go
// request DTOs legitimately share a TS type (e.g. create/update/platform user all
// mirror UserFormData); an identical shape is emitted once. Two DTOs claiming the
// same TS name with DIFFERENT fields is a real conflict — fail loud, don't pick one.
func dedupe(path string, group []dto) ([]dto, error) {
	seen := map[string]dto{}
	var uniq []dto
	for _, d := range group {
		if prev, ok := seen[d.dir.tsName]; ok {
			if !fieldsEqual(prev.fields, d.fields) {
				return nil, fmt.Errorf(
					"%s: TS type %q is defined by both %q and %q with different fields — "+
						"reconcile the Go DTOs or give them distinct //gkts: names",
					path, d.dir.tsName, prev.goName, d.goName)
			}
			continue // identical duplicate — one definition suffices
		}
		seen[d.dir.tsName] = d
		uniq = append(uniq, d)
	}
	return uniq, nil
}

func fieldsEqual(a, b []dtoField) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// renderType writes one `export type` block and records any imports its fields need.
func renderType(
	sb *strings.Builder,
	d dto,
	byGo map[string]directive,
	localNames map[string]bool,
	imports map[string]string,
) error {
	fmt.Fprintf(sb, "export type %s = {\n", d.dir.tsName)
	for _, f := range d.fields {
		tsType := f.tsType
		if f.dep != "" {
			ref, ok := byGo[f.dep]
			if !ok {
				return fmt.Errorf(
					"field %q references Go type %q, which has no //gkts: directive — annotate it or the reference cannot be typed",
					f.name, f.dep)
			}
			// Substitute the dependency's TS name for its Go name in the rendered type
			// (handles `userDTO`, `userDTO[]`, `userDTO | null`).
			tsType = strings.Replace(tsType, f.dep, ref.tsName, 1)
			if !localNames[ref.tsName] {
				imports[ref.tsName] = importSpec(ref.tsPath)
			}
		}
		opt := ""
		if f.optional {
			opt = "?"
		}
		fmt.Fprintf(sb, "    %s%s: %s;\n", f.name, opt, tsType)
	}
	sb.WriteString("};\n")
	return nil
}

// importSpec turns a repo-relative TS path into the '@/...' alias the frontend uses.
func importSpec(tsPath string) string {
	p := strings.TrimSuffix(tsPath, ".ts")
	p = strings.TrimPrefix(p, "assets/")
	return "@/" + p
}

func writeFiles(root string, files map[string]string) {
	for rel, content := range files {
		abs := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			fatal("mkdir %s: %v", filepath.Dir(abs), err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			fatal("write %s: %v", rel, err)
		}
		fmt.Printf("tsgen: wrote %s\n", rel)
	}
	for _, rel := range orphans(root, files) {
		if err := os.Remove(filepath.Join(root, rel)); err != nil {
			fatal("prune orphan %s: %v", rel, err)
		}
		fmt.Printf("tsgen: pruned orphan %s\n", rel)
	}
	fmt.Printf("tsgen: %d file(s) generated\n", len(files))
}

// checkFiles verifies each generated file matches disk; exits 1 on any drift. This
// is the CI gate: if a Go DTO changed without re-running `make ts-gen`, it fails.
func checkFiles(root string, files map[string]string) {
	var drift []string
	for rel, want := range files {
		got, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			drift = append(drift, rel+" (missing — run make ts-gen)")
			continue
		}
		if string(got) != want {
			drift = append(drift, rel+" (out of date — run make ts-gen)")
		}
	}
	for _, rel := range orphans(root, files) {
		drift = append(drift, rel+" (orphan — no //gkts directive produces it; run make ts-gen to prune)")
	}
	if len(drift) > 0 {
		sort.Strings(drift)
		fmt.Fprintln(os.Stderr, "tsgen: generated TypeScript is out of date:")
		for _, d := range drift {
			fmt.Fprintln(os.Stderr, "  - "+d)
		}
		os.Exit(1)
	}
	fmt.Printf("tsgen: %d file(s) up to date\n", len(files))
}

// orphans returns generated files still on disk (identified by the DO-NOT-EDIT
// header) that the CURRENT directive set no longer produces — a //gkts directive
// was deleted or its path repointed, leaving a stale, now-authorless TS type the
// frontend keeps importing. generate prunes them; check reports them as drift.
func orphans(root string, current map[string]string) []string {
	var out []string
	err := filepath.WalkDir(filepath.Join(root, "assets"), func(path string, e os.DirEntry, err error) error {
		if err != nil || e.IsDir() || !strings.HasSuffix(path, ".ts") {
			return nil
		}
		b, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		if !strings.HasPrefix(string(b), genHeader) {
			return nil
		}
		rel := filepath.ToSlash(mustRel(root, path))
		if _, live := current[rel]; !live {
			out = append(out, rel)
		}
		return nil
	})
	if err != nil {
		fatal("scan for orphans: %v", err)
	}
	sort.Strings(out)
	return out
}

func mustRel(base, path string) string {
	rel, err := filepath.Rel(base, path)
	if err != nil {
		fatal("rel %s: %v", path, err)
	}
	return rel
}

// repoRoot resolves the gokick module root by walking up from the working
// directory (tsgen runs from tools/tsgen).
func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal("getwd: %v", err)
	}
	for {
		mod := filepath.Join(dir, "go.mod")
		if b, err := os.ReadFile(mod); err == nil && strings.Contains(string(b), "module gokick\n") {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal("could not find gokick go.mod above %s", dir)
		}
		dir = parent
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "tsgen: "+format+"\n", args...)
	os.Exit(1)
}
