// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fmt"
	"gokick/app"
	"gokick/app/application/auth/command"
	"gokick/app/application/bus"
	"gokick/app/application/bus/middleware"
	query3 "gokick/app/application/dashboard/query"
	command4 "gokick/app/application/platform/command"
	query4 "gokick/app/application/platform/query"
	command2 "gokick/app/application/profile/command"
	"gokick/app/application/profile/query"
	run2 "gokick/app/application/run"
	command5 "gokick/app/application/tenant/command"
	query5 "gokick/app/application/tenant/query"
	command3 "gokick/app/application/user/command"
	query2 "gokick/app/application/user/query"
	run3 "gokick/app/domain/run"
	"gokick/app/domain/shared"
	token2 "gokick/app/domain/token"
	"gokick/app/infrastructure/config"
	"gokick/app/infrastructure/database"
	"gokick/app/infrastructure/scheduler"
	"gokick/app/infrastructure/security"
	"gokick/app/infrastructure/sqlite/audit"
	"gokick/app/infrastructure/sqlite/run"
	"gokick/app/infrastructure/sqlite/seeder"
	"gokick/app/infrastructure/sqlite/tenant"
	"gokick/app/infrastructure/sqlite/token"
	"gokick/app/infrastructure/sqlite/user"
	"gokick/app/infrastructure/worker"
	"gokick/app/presentation/console"
	"gokick/app/presentation/http/handler"
	middleware2 "gokick/app/presentation/http/middleware"
	"gokick/app/presentation/http/response"
	"gokick/app/presentation/http/server"
	"gokick/public"
	"io/fs"
	"log/slog"
	"time"
)

// Injectors from container_provider.go:

func CreateApplication(logger *slog.Logger, reporter shared.ErrorReporter) (*app.Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	jwtService, err := security.NewJwtService(configConfig)
	if err != nil {
		return nil, err
	}
	responder := response.NewResponder(logger)
	ipExtractor := provideIPExtractor(configConfig)
	rateLimiters, err := provideRateLimiters(configConfig, ipExtractor, logger)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler(responder)
	fs := providePublicFS()
	spaConfig := provideSPAConfig(configConfig)
	spaHandler := handler.NewSPAHandler(responder, logger, fs, spaConfig)
	cookieSecure := provideCookieSecure(configConfig)
	sqliteManager, err := database.NewSqliteManager(configConfig)
	if err != nil {
		return nil, err
	}
	permissionChecker := providePermissionChecker()
	v := provideEventHandlers()
	eventBus := provideEventBus(logger, v, reporter)
	repository := run.NewRepository(sqliteManager)
	handlerRegistry, err := provideRunHandlerRegistry(configConfig)
	if err != nil {
		return nil, err
	}
	runDispatcher := provideRunDispatcher(repository, handlerRegistry)
	auditRepository := audit.NewRepository(sqliteManager)
	tenantResolver := provideTenantResolver()
	commandBus := provideCommandBus(logger, sqliteManager, permissionChecker, eventBus, runDispatcher, auditRepository, reporter, tenantResolver)
	userRepository := user.NewRepository(sqliteManager)
	tokenRepository := token.NewRepository(sqliteManager)
	passwordHasher := providePasswordHasher()
	loginHandler := command.NewLoginHandler(userRepository, tokenRepository, passwordHasher, jwtService)
	refreshTokenHandler := command.NewRefreshTokenHandler(userRepository, tokenRepository, jwtService)
	logoutHandler := command.NewLogoutHandler(tokenRepository)
	permissionsRegistry := providePermissionsRegistry()
	authHandler := handler.NewAuthHandler(responder, cookieSecure, commandBus, loginHandler, refreshTokenHandler, logoutHandler, permissionsRegistry)
	queryBus := provideQueryBus(logger, permissionChecker, reporter, tenantResolver)
	getProfileHandler := query.NewGetProfileHandler(userRepository)
	changePasswordHandler := command2.NewChangePasswordHandler(userRepository, passwordHasher)
	profileHandler := handler.NewProfileHandler(responder, commandBus, queryBus, getProfileHandler, changePasswordHandler, permissionsRegistry)
	listUsersHandler := query2.NewListUsersHandler(userRepository)
	getUserHandler := query2.NewGetUserHandler(userRepository)
	multitenancy := provideMultitenancy(configConfig)
	createUserHandler := command3.NewCreateUserHandler(userRepository, passwordHasher, multitenancy)
	updateUserHandler := command3.NewUpdateUserHandler(userRepository, passwordHasher)
	deleteUserHandler := command3.NewDeleteUserHandler(userRepository)
	bulkDeleteUsersHandler := command3.NewBulkDeleteUsersHandler(userRepository)
	bulkSetUsersActiveHandler := command3.NewBulkSetUsersActiveHandler(userRepository)
	adminUsersHandler := handler.NewAdminUsersHandler(responder, commandBus, queryBus, listUsersHandler, getUserHandler, createUserHandler, updateUserHandler, deleteUserHandler, bulkDeleteUsersHandler, bulkSetUsersActiveHandler)
	getUserDashboardHandler := query3.NewGetUserDashboardHandler()
	getAdminDashboardHandler := query3.NewGetAdminDashboardHandler(userRepository)
	dashboardHandler := handler.NewDashboardHandler(responder, queryBus, getUserDashboardHandler, getAdminDashboardHandler)
	tenantRepository := tenant.NewRepository(sqliteManager)
	getStatsHandler := query4.NewGetStatsHandler(tenantRepository, userRepository)
	listAllUsersHandler := query4.NewListAllUsersHandler(userRepository)
	queryGetUserHandler := query4.NewGetUserHandler(userRepository)
	listTenantsHandler := query4.NewListTenantsHandler(tenantRepository)
	createPlatformUserHandler := command4.NewCreatePlatformUserHandler(userRepository, tenantRepository, passwordHasher)
	updatePlatformUserHandler := command4.NewUpdatePlatformUserHandler(userRepository, passwordHasher)
	deletePlatformUserHandler := command4.NewDeletePlatformUserHandler(userRepository)
	bulkDeletePlatformUsersHandler := command4.NewBulkDeletePlatformUsersHandler(userRepository)
	bulkSetPlatformUsersActiveHandler := command4.NewBulkSetPlatformUsersActiveHandler(userRepository)
	createTenantHandler := command5.NewCreateTenantHandler(tenantRepository)
	deletePlatformTenantHandler := command4.NewDeletePlatformTenantHandler(tenantRepository)
	bulkDeletePlatformTenantsHandler := command4.NewBulkDeletePlatformTenantsHandler(tenantRepository)
	platformHandler := handler.NewPlatformHandler(responder, queryBus, commandBus, getStatsHandler, listAllUsersHandler, queryGetUserHandler, listTenantsHandler, createPlatformUserHandler, updatePlatformUserHandler, deletePlatformUserHandler, bulkDeletePlatformUsersHandler, bulkSetPlatformUsersActiveHandler, createTenantHandler, deletePlatformTenantHandler, bulkDeletePlatformTenantsHandler)
	debugRunHandler := handler.NewDebugRunHandler(responder, repository)
	serverServer := server.NewServer(configConfig, logger, reporter, jwtService, responder, rateLimiters, ipExtractor, healthHandler, spaHandler, authHandler, profileHandler, adminUsersHandler, dashboardHandler, platformHandler, debugRunHandler)
	v2 := provideSchedulerJobs(tokenRepository)
	scheduler, err := provideScheduler(logger, v2)
	if err != nil {
		return nil, err
	}
	runWorker := provideRunWorker(logger, reporter, repository, handlerRegistry, runDispatcher, sqliteManager, auditRepository, configConfig)
	serveCommand := console.NewServeCommand(serverServer, scheduler, runWorker)
	seedAdminPassword := provideSeedAdminPassword(configConfig)
	seedSuperAdminPassword := provideSeedSuperAdminPassword(configConfig)
	seedAdminTenant := provideSeedAdminTenant(configConfig)
	multitenant := provideMultitenant(configConfig)
	seederSeeder := seeder.NewSeeder(userRepository, tenantRepository, passwordHasher, seedAdminPassword, seedSuperAdminPassword, seedAdminTenant, multitenant, logger)
	systemCommandBus := provideSystemCommandBus(logger, sqliteManager, eventBus, auditRepository, runDispatcher, reporter)
	seedCommand := console.NewSeedCommand(seederSeeder, systemCommandBus)
	getTenantHandler := query5.NewGetTenantHandler(tenantRepository)
	createUserCommand := console.NewCreateUserCommand(createUserHandler, createTenantHandler, getTenantHandler, configConfig, systemCommandBus)
	createSuperAdminHandler := command4.NewCreateSuperAdminHandler(userRepository, passwordHasher)
	createSuperAdminCommand := console.NewCreateSuperAdminCommand(createSuperAdminHandler, systemCommandBus)
	createTenantCommand := console.NewCreateTenantCommand(createTenantHandler, systemCommandBus)
	workerCommand := console.NewWorkerCommand(runWorker)
	rootCommand := console.NewRootCommand(serveCommand, seedCommand, createUserCommand, createSuperAdminCommand, createTenantCommand, workerCommand)
	migrationManager := database.NewMigrationManager(sqliteManager, logger)
	application := app.NewApplication(rootCommand, migrationManager)
	return application, nil
}

// container_provider.go:

func providePasswordHasher() shared.PasswordHasher {
	return security.NewPasswordHasher()
}

func providePermissionChecker() shared.PermissionChecker {
	return security.NewPermissionChecker()
}

// provideTenantResolver wires the single-tenant default resolver (multitenancy
// off). Swapping this binding is how a multi-tenant deployment turns isolation
// on without touching handlers.
func provideTenantResolver() shared.TenantResolver {
	return security.NewDefaultTenantResolver()
}

// provideCommandBus wires the write-side bus from busmw.CommandChain (the single
// source of the chain order, shared with testfx so they can't drift).
func provideCommandBus(
	logger *slog.Logger,
	db *database.SqliteManager,
	checker shared.PermissionChecker,
	eventBus *bus.EventBus,
	runDispatcher shared.RunDispatcher, audit2 shared.AuditLogger,

	reporter shared.ErrorReporter,
	tenantResolver shared.TenantResolver,
) *bus.CommandBus {
	return bus.NewCommandBus(middleware.CommandChain(
		logger,
		checker,
		reporter,
		tenantResolver, audit2, runDispatcher,
		eventBus,
		db,
	)...,
	)
}

// provideSystemCommandBus wires the OPERATOR-TRUSTED write bus for the CLI
// create-* commands. It is the CommandBus chain MINUS Authorize and Tenant (no
// principal, no JWT-resolved tenant). Audit still wraps OUTSIDE Transaction and
// DispatchEvents still wraps it, and RunDispatcher sits between them so an event
// handler on this bus can durably enqueue a follow-up run (F-008). See
// bus.SystemCommandBus.
func provideSystemCommandBus(
	logger *slog.Logger,
	db *database.SqliteManager,
	eventBus *bus.EventBus, audit2 shared.AuditLogger,

	runDispatcher shared.RunDispatcher,
	reporter shared.ErrorReporter,
) *bus.SystemCommandBus {
	return bus.NewSystemCommandBus(middleware.SystemChain(logger, db, eventBus, audit2, runDispatcher, reporter)...,
	)
}

func provideQueryBus(
	logger *slog.Logger,
	checker shared.PermissionChecker,
	reporter shared.ErrorReporter,
	tenantResolver shared.TenantResolver,
) *bus.QueryBus {
	return bus.NewQueryBus(middleware.BaseChain(logger, checker, reporter, tenantResolver)...)
}

func providePublicFS() fs.FS {
	return public.FS
}

// provideSPAConfig narrows *config.Config down to the deployment-specific
// frontend values the SPA handler injects into index.html, keeping the handler
// layer free of an infrastructure/config import.
func provideSPAConfig(cfg *config.Config) handler.SPAConfig {
	return handler.SPAConfig{
		SentryDSN:         cfg.FrontendSentryDSN,
		SentryEnvironment: cfg.SentryEnvironment,
		SentryDebug:       cfg.SentryDebug,
	}
}

// provideEventHandlers is the single source of truth for event subscriptions
// — mirrors providePermissionsRegistry / provideSchedulerJobs. Add a new
// entry here; provideEventBus wires them up during construction.
func provideEventHandlers() []bus.EventHandlerEntry {
	return []bus.EventHandlerEntry{}
}

func provideEventBus(
	logger *slog.Logger,
	handlers []bus.EventHandlerEntry,
	reporter shared.ErrorReporter,
) *bus.EventBus {
	eb := bus.NewEventBus(middleware.RecoveryMiddleware(logger, reporter), middleware.LoggingMiddleware(logger))
	for _, h := range handlers {
		eb.Register(h.Event, h.Handler)
	}
	return eb
}

func provideCookieSecure(cfg *config.Config) handler.CookieSecure {
	return handler.CookieSecure(cfg.CookieSecure)
}

// provideIPExtractor is the single source of truth for how a request's
// client IP is resolved — rate limiters and the audit IP middleware both
// pull from it so flipping APP_TRUST_PROXY_HEADERS keeps them in sync.
func provideIPExtractor(cfg *config.Config) middleware2.IPExtractor {
	return middleware2.NewIPExtractor(cfg.TrustProxyHeaders)
}

// provideRateLimiters parses the configured per-IP buckets at startup so a
// malformed APP_RATE_LIMIT_* fails fast instead of silently disabling
// protection.
func provideRateLimiters(
	cfg *config.Config,
	extract middleware2.IPExtractor,
	logger *slog.Logger,
) (*server.RateLimiters, error) {
	loginRule, err := middleware2.ParseRateRule(cfg.RateLimitLogin)
	if err != nil {
		return nil, fmt.Errorf("APP_RATE_LIMIT_LOGIN: %w", err)
	}
	refreshRule, err := middleware2.ParseRateRule(cfg.RateLimitRefresh)
	if err != nil {
		return nil, fmt.Errorf("APP_RATE_LIMIT_REFRESH: %w", err)
	}
	return &server.RateLimiters{
		Login:   middleware2.NewRateLimiter(loginRule, extract, logger),
		Refresh: middleware2.NewRateLimiter(refreshRule, extract, logger),
	}, nil
}

// provideSeedAdminPassword surfaces the seed admin password as a distinct
// Wire-bound type so the seeder's constructor can take it without colliding
// with other strings in the DI graph.
func provideSeedAdminPassword(cfg *config.Config) seeder.SeedAdminPassword {
	return seeder.SeedAdminPassword(cfg.SeedAdminPassword)
}

// provideSeedSuperAdminPassword surfaces the OPTIONAL superadmin seed password
// as its own Wire-bound type. Empty = no superadmin seeded.
func provideSeedSuperAdminPassword(cfg *config.Config) seeder.SeedSuperAdminPassword {
	return seeder.SeedSuperAdminPassword(cfg.SeedSuperAdminPassword)
}

// provideSeedAdminTenant / provideMultitenant surface the seeder's tenant inputs
// as Wire-distinct types so it gets the specific values, not the whole config.
func provideSeedAdminTenant(cfg *config.Config) seeder.SeedAdminTenant {
	return seeder.SeedAdminTenant(cfg.SeedAdminTenant)
}

func provideMultitenant(cfg *config.Config) seeder.Multitenant {
	return seeder.Multitenant(cfg.Multitenancy)
}

// provideMultitenancy surfaces APP_MULTITENANCY to application-layer constructors
// (the create-user handler) that fail-close tenant resolution but cannot import
// infrastructure. shared.Multitenancy is the Wire-distinct domain type.
func provideMultitenancy(cfg *config.Config) shared.Multitenancy {
	return shared.Multitenancy(cfg.Multitenancy)
}

// provideSchedulerJobs is the single source of truth for periodic in-process
// jobs — mirrors providePermissionsRegistry. Add
// a new Job here; provideScheduler stays decoupled from job business.
//
// Jobs run with NO tenant in ctx: under APP_MULTITENANCY=true a Fn that touches
// a tenant-owned table (r.Tenant(ctx)) panics on every tick, log-only, forever.
// Tenant-scoped work belongs in a run (tenant stamped at enqueue) or must
// resolve tenants explicitly.
func provideSchedulerJobs(tokens token2.Repository) []scheduler.Job {
	return []scheduler.Job{
		{
			Name:     "cleanup:expired-refresh-tokens",
			Interval: 1 * time.Hour,
			Fn:       tokens.DeleteExpired,
		},
	}
}

func provideScheduler(logger *slog.Logger, jobs []scheduler.Job) (*scheduler.Scheduler, error) {
	return scheduler.NewScheduler(logger, jobs)
}

// provideRunHandlerRegistry collects every kind → durable-run handler the binary
// can process. Real handlers are registered here as they appear. When APP_RUN_DEBUG
// is on it also registers the e2e:* debug kinds (the crash-recovery / drain
// harness) — never in production. The default lease comes from config so an unset
// per-kind lease stays consistent.
func provideRunHandlerRegistry(cfg *config.Config) (*run2.HandlerRegistry, error) {
	kinds := map[string]run2.Registration{}
	if cfg.RunDebug {
		for kind, reg := range run2.E2EDebugRegistrations() {
			kinds[kind] = reg
		}
	}
	return run2.NewHandlerRegistry(kinds, cfg.RunWorkerLease)
}

// provideRunDispatcher returns the durable-run dispatcher as a domain interface so
// command/event handlers depend on shared.RunDispatcher, not the concrete type.
func provideRunDispatcher(
	repo run3.Repository,
	registry *run2.HandlerRegistry,
) shared.RunDispatcher {
	return run2.NewDispatcher(repo, registry)
}

// provideRunWorker wires the durable run worker (the one background-work engine) from
// config. It injects the run dispatcher (so a handler can enqueue a child task), the
// SqliteManager as the Transactor backing shared.WithTx (short atomic writes the handler
// scopes itself), and the AuditLogger so a run handler's audit events are drained and
// persisted — the worker bypasses the bus, where these are normally injected.
func provideRunWorker(
	logger *slog.Logger,
	reporter shared.ErrorReporter,
	repo run3.Repository,
	registry *run2.HandlerRegistry,
	runDispatcher shared.RunDispatcher,
	db *database.SqliteManager, audit2 shared.AuditLogger,

	cfg *config.Config,
) *worker.RunWorker {
	return worker.NewRunWorker(
		logger,
		reporter,
		repo,
		registry,
		runDispatcher,
		db, audit2, worker.RunWorkerConfig{
			DefaultLease:      cfg.RunWorkerLease,
			HeartbeatInterval: cfg.RunWorkerHeartbeat,
			PollInterval:      cfg.RunWorkerPoll,
			DrainTimeout:      cfg.RunWorkerDrainTimeout,
			MaxInFlight:       cfg.RunWorkerMaxInFlight,
			MaxReclaims:       cfg.RunWorkerMaxReclaims,
		},
	)
}

func providePermissionsRegistry() *shared.PermissionsRegistry {
	return shared.NewPermissionsRegistry([]shared.Permissioned{command.LogoutCommand{}, command2.ChangePasswordCommand{}, query.GetProfileQuery{}, command3.CreateUserCommand{}, command3.UpdateUserCommand{}, command3.DeleteUserCommand{}, query2.ListUsersQuery{}, query2.GetUserQuery{}, query3.GetUserDashboardQuery{}, query3.GetAdminDashboardQuery{}, query4.ListAllUsersQuery{}, query4.GetUserQuery{}, query4.ListTenantsQuery{}, query4.GetStatsQuery{}, command3.BulkDeleteUsersCommand{}, command3.BulkSetUsersActiveCommand{}, command4.CreatePlatformUserCommand{}, command4.UpdatePlatformUserCommand{}, command4.BulkDeletePlatformUsersCommand{}, command4.BulkSetPlatformUsersActiveCommand{}, command4.DeletePlatformUserCommand{}, command4.DeletePlatformTenantCommand{}, command4.BulkDeletePlatformTenantsCommand{}, command5.CreateTenantCommand{}, command4.CreateSuperAdminCommand{}, query5.GetTenantQuery{}})
}
