// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gokick/app"
	"gokick/app/application/bus"
	"gokick/app/application/bus/middleware"
	"gokick/app/domain/shared"
	"gokick/app/infrastructure/config"
	"gokick/app/infrastructure/database"
	"gokick/app/infrastructure/security"
	"gokick/app/infrastructure/sqlite"
	"gokick/app/infrastructure/sqlite/token"
	"gokick/app/infrastructure/sqlite/user"
	"gokick/app/presentation/console"
	"gokick/app/presentation/http/handler"
	"gokick/app/presentation/http/server"
	"gokick/public"
	"io/fs"
	"log/slog"
)

// Injectors from container_provider.go:

func CreateApplication(logger *slog.Logger) (*app.Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	fs := providePublicFS()
	spaHandler := handler.NewSPAHandler(fs)
	serverServer := server.NewServer(configConfig, logger, healthHandler, spaHandler)
	serveCommand := console.NewServeCommand(serverServer)
	sqliteManager, err := database.NewSqliteManager(configConfig)
	if err != nil {
		return nil, err
	}
	repository := user.NewRepository(sqliteManager)
	passwordHasher := providePasswordHasher()
	seeder := sqlite.NewSeeder(repository, passwordHasher, logger)
	seedCommand := console.NewSeedCommand(seeder)
	rootCommand := console.NewRootCommand(serveCommand, seedCommand)
	migrationManager := database.NewMigrationManager(sqliteManager, logger)
	eventCollector := provideEventCollector()
	permissionChecker := providePermissionChecker()
	eventBus := provideEventBus(logger)
	commandBus := provideCommandBus(logger, sqliteManager, eventCollector, permissionChecker, eventBus)
	queryBus := provideQueryBus(logger, permissionChecker)
	jwtService, err := security.NewJwtService(configConfig)
	if err != nil {
		return nil, err
	}
	tokenRepository := token.NewRepository(sqliteManager)
	application := app.NewApplication(rootCommand, migrationManager, commandBus, queryBus, eventBus, jwtService, tokenRepository)
	return application, nil
}

// container_provider.go:

func provideEventCollector() *shared.EventCollector {
	return shared.NewEventCollector()
}

func providePasswordHasher() shared.PasswordHasher {
	return security.NewPasswordHasher()
}

func providePermissionChecker() shared.PermissionChecker {
	return security.NewPermissionChecker()
}

func provideCommandBus(
	logger *slog.Logger,
	db *database.SqliteManager,
	collector *shared.EventCollector,
	checker shared.PermissionChecker,
	eventBus *bus.EventBus,
) *bus.CommandBus {
	return bus.NewCommandBus(middleware.RecoveryMiddleware(logger), middleware.LoggingMiddleware(logger), middleware.AuthorizeMiddleware(checker), middleware.TransactionMiddleware(db), middleware.DispatchEventsMiddleware(logger, collector, eventBus))
}

func provideQueryBus(logger *slog.Logger, checker shared.PermissionChecker) *bus.QueryBus {
	return bus.NewQueryBus(middleware.RecoveryMiddleware(logger), middleware.LoggingMiddleware(logger), middleware.AuthorizeMiddleware(checker))
}

func providePublicFS() fs.FS {
	return public.FS
}

func provideEventBus(logger *slog.Logger) *bus.EventBus {
	return bus.NewEventBus(middleware.RecoveryMiddleware(logger), middleware.LoggingMiddleware(logger))
}
