// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gokick/app"
	"gokick/app/application/auth/command"
	"gokick/app/application/bus"
	"gokick/app/application/bus/middleware"
	query3 "gokick/app/application/dashboard/query"
	command2 "gokick/app/application/profile/command"
	"gokick/app/application/profile/query"
	command3 "gokick/app/application/user/command"
	query2 "gokick/app/application/user/query"
	"gokick/app/domain/shared"
	"gokick/app/infrastructure/config"
	"gokick/app/infrastructure/database"
	"gokick/app/infrastructure/security"
	"gokick/app/infrastructure/sqlite"
	"gokick/app/infrastructure/sqlite/token"
	"gokick/app/infrastructure/sqlite/user"
	"gokick/app/presentation/console"
	"gokick/app/presentation/http/handler"
	"gokick/app/presentation/http/server"
	"gokick/public"
	"io/fs"
	"log/slog"
)

// Injectors from container_provider.go:

func CreateApplication(logger *slog.Logger) (*app.Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	jwtService, err := security.NewJwtService(configConfig)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	fs := providePublicFS()
	spaHandler := handler.NewSPAHandler(fs)
	cookieSecure := provideCookieSecure(configConfig)
	sqliteManager, err := database.NewSqliteManager(configConfig)
	if err != nil {
		return nil, err
	}
	permissionChecker := providePermissionChecker()
	eventBus := provideEventBus(logger)
	commandBus := provideCommandBus(logger, sqliteManager, permissionChecker, eventBus)
	repository := user.NewRepository(sqliteManager)
	tokenRepository := token.NewRepository(sqliteManager)
	passwordHasher := providePasswordHasher()
	loginHandler := command.NewLoginHandler(repository, tokenRepository, passwordHasher, jwtService)
	refreshTokenHandler := command.NewRefreshTokenHandler(repository, tokenRepository, jwtService)
	logoutHandler := command.NewLogoutHandler(tokenRepository)
	permissionsRegistry := providePermissionsRegistry()
	authHandler := handler.NewAuthHandler(cookieSecure, commandBus, loginHandler, refreshTokenHandler, logoutHandler, permissionsRegistry)
	queryBus := provideQueryBus(logger, permissionChecker)
	getProfileHandler := query.NewGetProfileHandler(repository)
	changePasswordHandler := command2.NewChangePasswordHandler(repository, passwordHasher)
	profileHandler := handler.NewProfileHandler(commandBus, queryBus, getProfileHandler, changePasswordHandler, permissionsRegistry)
	listUsersHandler := query2.NewListUsersHandler(repository)
	createUserHandler := command3.NewCreateUserHandler(repository, passwordHasher)
	updateUserHandler := command3.NewUpdateUserHandler(repository, passwordHasher)
	deleteUserHandler := command3.NewDeleteUserHandler(repository)
	adminUsersHandler := handler.NewAdminUsersHandler(commandBus, queryBus, listUsersHandler, createUserHandler, updateUserHandler, deleteUserHandler)
	getUserDashboardHandler := query3.NewGetUserDashboardHandler()
	getAdminDashboardHandler := query3.NewGetAdminDashboardHandler()
	dashboardHandler := handler.NewDashboardHandler(queryBus, getUserDashboardHandler, getAdminDashboardHandler)
	serverServer := server.NewServer(configConfig, logger, jwtService, healthHandler, spaHandler, authHandler, profileHandler, adminUsersHandler, dashboardHandler)
	serveCommand := console.NewServeCommand(serverServer)
	seeder := sqlite.NewSeeder(repository, passwordHasher, logger)
	seedCommand := console.NewSeedCommand(seeder)
	createUserCommand := console.NewCreateUserCommand(createUserHandler)
	rootCommand := console.NewRootCommand(serveCommand, seedCommand, createUserCommand)
	migrationManager := database.NewMigrationManager(sqliteManager, logger)
	application := app.NewApplication(rootCommand, migrationManager)
	return application, nil
}

// container_provider.go:

func providePasswordHasher() shared.PasswordHasher {
	return security.NewPasswordHasher()
}

func providePermissionChecker() shared.PermissionChecker {
	return security.NewPermissionChecker()
}

func provideCommandBus(
	logger *slog.Logger,
	db *database.SqliteManager,
	checker shared.PermissionChecker,
	eventBus *bus.EventBus,
) *bus.CommandBus {
	chain := append(middleware.BaseChain(logger, checker), middleware.DispatchEventsMiddleware(logger, eventBus), middleware.TransactionMiddleware(db))
	return bus.NewCommandBus(chain...)
}

func provideQueryBus(logger *slog.Logger, checker shared.PermissionChecker) *bus.QueryBus {
	return bus.NewQueryBus(middleware.BaseChain(logger, checker)...)
}

func providePublicFS() fs.FS {
	return public.FS
}

func provideEventBus(logger *slog.Logger) *bus.EventBus {
	return bus.NewEventBus(middleware.RecoveryMiddleware(logger), middleware.LoggingMiddleware(logger))
}

// provideCookieSecure extracts the boolean flag so handler.NewAuthHandler
// does not need to import the config package.
func provideCookieSecure(cfg *config.Config) handler.CookieSecure {
	return handler.CookieSecure(cfg.CookieSecure)
}

// providePermissionsRegistry collects RequiredPermission() values from every
// command/query handler that is Permissioned. Adding a new handler requires
// adding it here too — there is no other permission list in the codebase.
func providePermissionsRegistry() *shared.PermissionsRegistry {
	return shared.NewPermissionsRegistry([]shared.Permissioned{command.LogoutCommand{}, command2.ChangePasswordCommand{}, query.GetProfileQuery{}, command3.CreateUserCommand{}, command3.UpdateUserCommand{}, command3.DeleteUserCommand{}, query2.ListUsersQuery{}, query3.GetUserDashboardQuery{}, query3.GetAdminDashboardQuery{}})
}
