// Code generated by tsgen; DO NOT EDIT.

import { isNumber, isRecord } from '@/app-ui/Fetch/guards';

export type AdminDashboardResponse = {
    users_active: number;
    users_total: number;
};

export const isAdminDashboardResponse = (v: unknown): v is AdminDashboardResponse =>
    isRecord(v)
    && isNumber(v['users_active'])
    && isNumber(v['users_total']);
