// Code generated by tsgen; DO NOT EDIT.

import { isRecord, isString } from '@/app-ui/Fetch/guards';

export type DashboardResponse = {
    nickname: string;
};

export const isDashboardResponse = (v: unknown): v is DashboardResponse =>
    isRecord(v)
    && isString(v['nickname']);
