// Package i18n (the `gk i18n` subcommand) owns the single translation
// namespace in locale/messages.<lang>.json — ALL user-facing texts (UI labels
// and error messages alike) in frontend syntax ({param} placeholders, CLDR
// plural objects). The API ships {key, params} over the wire and the frontend
// renders every text, so the JSON catalogs are the one source of truth.
//
// The catalog FILENAMES are equally authoritative: they are the only place the
// supported-language set is declared by hand. Every other declaration of it is
// an artifact generated from them, so adding a language is a catalog file (plus
// a flag in the switcher) and `make i18n-gen` — never a hand edit in Go or TS:
//
//   - app/domain/shared/msgkey/keys.gen.go — one Go constant per key, so a
//     typo at an error call site is a compile error;
//   - app/domain/shared/lang_gen.go — the Lang constants, SupportedLangs and
//     ParseLang;
//   - assets/app-ui/I18n/langs.gen.ts — SUPPORTED_LANGS, the Lang union and
//     CANONICAL_LANG;
//   - assets/app-ui/I18n/catalog/<lang>.ts — the catalogs the t() renderer
//     consumes, and catalogs.gen.ts, the language→catalog record it looks up in.
//
// The CLDR plural categories each language can select are NOT cached: both
// `generate` and `check` read them out of Node's Intl.PluralRules, the same
// implementation the renderer selects forms with. A committed table would be
// byte-compared against itself and would ratify a wrong entry forever, so this
// one input is derived live — which is why `check` needs node on PATH.
//
// `gk i18n check` additionally gates catalog quality (key format, key + param
// + pluralness parity against the canonical catalog, valid CLDR forms, every
// category the language can select, lowercase-first params), artifact
// freshness, dead keys (unused in BOTH Go production code and frontend
// source), and Go and frontend call sites whose params miss a placeholder.
//
// Usage:
//
//	gk i18n generate   # (re)write every artifact above
//	gk i18n check      # verify artifacts match + run all gates; exit 1 on drift
package i18n

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"gokick-gk/internal/tool"
)

const (
	prefix      = "gk i18n"
	catalogDir  = "locale"
	keysOutPath = "app/domain/shared/msgkey/keys.gen.go"
	tsOutDir    = "assets/app-ui/I18n/catalog"
	genHeader   = "// Code generated by gk i18n; DO NOT EDIT."

	// The language-set artifacts. Everything that used to declare "which
	// languages exist" by hand is written from the discovered catalogs, so the
	// filenames in locale/ are the only declaration left to keep in step.
	langsGoOutPath = "app/domain/shared/lang_gen.go"
	langsTSOutPath = "assets/app-ui/I18n/langs.gen.ts"
	catalogsTSPath = "assets/app-ui/I18n/catalogs.gen.ts"

	msgkeyImportPath = "gokick/app/domain/shared/msgkey"
	// feLangModule is assets/app-ui/I18n/lang.ts as an alias import specifier
	// — the one hand-written module a generated catalog may reference.
	feLangModule = "@/app-ui/I18n/lang"
	// feCatalogModule is the generated-catalog directory as an import prefix.
	feCatalogModule = "@/app-ui/I18n/catalog"

	// canonicalLang is the catalog the Go constants and the frontend key union
	// derive from, and the language served at bare URLs. It is the ONE place
	// the canonical language is written down: shared.DefaultLang and the
	// frontend CANONICAL_LANG are both generated from it. The language SET is
	// discovered from the locale/messages.<lang>.json filenames, so this tool
	// keeps no list of its own to drift from the ones it generates.
	canonicalLang = "en"
)

var (
	// keyRe: dot-separated snake_case with at least two segments
	// ("user.nickname_required").
	keyRe = regexp.MustCompile(`^[a-z0-9]+(?:_[a-z0-9]+)*(?:\.[a-z0-9]+(?:_[a-z0-9]+)*)+$`)
	// paramRe: frontend-syntax placeholder — {count}, {nickname}. Lowercase
	// first letter enforced; braceTokenRe catches the ones that are not.
	paramRe      = regexp.MustCompile(`\{([a-z][A-Za-z0-9_]*)\}`)
	braceTokenRe = regexp.MustCompile(`\{([A-Za-z0-9_]+)\}`)
	// langTokenRe: the language token of a catalog filename. It is emitted
	// verbatim as a TS identifier (`<lang>Catalog`), so a region-subtagged tag
	// ("pt-BR") would generate `export const pt-BRCatalog` — a file no gate
	// reads back but every build parses. Matches shared.ParseLang, which
	// likewise accepts bare lowercase tags only.
	langTokenRe = regexp.MustCompile(`^[a-z][a-z0-9]*$`)
)

// initialisms rendered uppercase in generated const names (Go naming style).
var initialisms = map[string]string{
	"json": "JSON",
	"id":   "ID",
	"url":  "URL",
	"http": "HTTP",
	"api":  "API",
}

// cldrForms are the valid plural categories in a message object; cldrOrder is
// the emission order for the generated TS catalogs.
var (
	cldrForms = map[string]bool{
		"zero": true, "one": true, "two": true, "few": true, "many": true, "other": true,
	}
	cldrOrder = []string{"zero", "one", "two", "few", "many", "other"}
)

// pluralForms maps a language to the CLDR categories its plural rules can
// actually SELECT, as opposed to cldrForms, which only says a name is legal.
// A catalog omitting one of these is silently wrong rather than broken: the
// renderer falls back to "other" with no report, so Czech without "few" reads
// the 5+ genitive at 2/3/4.
//
// Go ships no CLDR plural data, so the table is read at EVERY run out of the
// one authority that agrees with the renderer by construction — the frontend's
// own Intl.PluralRules. Deriving it live rather than committing it is the
// difference between a gate and a ritual: a committed table would be compared
// byte-for-byte against itself, so a wrong entry (a hand-resolved merge, an
// older ICU that predates a language gaining a category) would ratify itself
// forever and quietly stop demanding the form it exists to demand.
//
// It is threaded through validation rather than kept in a package var for the
// same reason: a global would let a test that never loaded it validate against
// an empty table and pass vacuously.
type pluralForms map[string][]string

// tsGenHeader banners the generated TS files whose source is the catalog SET
// rather than any single catalog file.
const tsGenHeader = "// Code generated by gk i18n from locale/; DO NOT EDIT — " +
	"add a catalog and run make i18n-gen.\n\n"

// message is one catalog entry: plain text or CLDR plural forms.
type message struct {
	single string
	forms  map[string]string // nil for a plain-text message
}

// texts returns every text variant of the message.
func (m message) texts() []string {
	if m.forms == nil {
		return []string{m.single}
	}
	out := make([]string, 0, len(m.forms))
	for _, form := range slices.Sorted(maps.Keys(m.forms)) {
		out = append(out, m.forms[form])
	}
	return out
}

// params returns the sorted set of {param} placeholders the message
// references across all its forms.
func (m message) params() []string {
	set := map[string]bool{}
	for _, text := range m.texts() {
		for _, match := range paramRe.FindAllStringSubmatch(text, -1) {
			set[match[1]] = true
		}
	}
	return slices.Sorted(maps.Keys(set))
}

func Run(args []string) {
	if len(args) != 1 || (args[0] != "generate" && args[0] != "check") {
		tool.Fatalf(prefix, "usage: gk i18n generate|check")
	}
	root, err := tool.RepoRoot()
	if err != nil {
		tool.Fatalf(prefix, "%v", err)
	}

	catalogs, err := loadCatalogs(filepath.Join(root, filepath.FromSlash(catalogDir)))
	if err != nil {
		tool.Fatalf(prefix, "%v", err)
	}
	langs := slices.Sorted(maps.Keys(catalogs))
	generating := args[0] == "generate"

	// Derived here, on every run and for every language — including while
	// CHECKING. Caching this in the repo would make the gate self-ratifying;
	// see the pluralForms doc.
	plurals, err := cldrPluralForms(langs)
	if err != nil {
		tool.Fatalf(prefix, "%v", err)
	}
	if problems := validateCatalogs(catalogs, plurals); len(problems) > 0 {
		fail(problems)
	}

	artifacts, err := renderArtifacts(catalogs, langs)
	if err != nil {
		tool.Fatalf(prefix, "%v", err)
	}

	if generating {
		if err := tool.WriteArtifacts(prefix, root, artifacts); err != nil {
			tool.Fatalf(prefix, "%v", err)
		}
		fmt.Printf("%s: %d keys in %d languages (%s)\n",
			prefix, len(catalogs[canonicalLang]), len(langs), strings.Join(langs, ", "))
		return
	}

	canonical := catalogs[canonicalLang]
	problems := tool.CheckArtifacts(root, artifacts, "make i18n-gen")
	// Both Go gates read the same one-pass scan of app/ + cmd/.
	scan, err := scanProductionGo(root)
	if err != nil {
		problems = append(problems, err.Error())
	} else {
		problems = append(problems, checkUsage(root, canonical, scan)...)
		problems = append(problems, checkCallSiteParams(canonical, scan)...)
	}
	problems = append(problems, checkFrontendCallSiteParams(root, canonical)...)
	if len(problems) > 0 {
		fail(problems)
	}
}

func fail(problems []string) {
	for _, p := range problems {
		fmt.Fprintf(os.Stderr, "%s: %s\n", prefix, p)
	}
	os.Exit(1)
}

// renderArtifacts produces every generated file (repo-relative path → exact
// content) from the catalogs: the message-key constants from the canonical
// one, a TS catalog per discovered language, and — from the discovered
// language SET — the Go and frontend declarations of it. Rendering the
// language set here rather than gating hand-written copies of it is what makes
// `check` byte-exact instead of set-comparing: a hand edit to any of them is
// stale, not merely divergent. TestRenderArtifactsCoversEveryGeneratedPath
// pins the key set, because a path dropped from this map is not merely
// ungenerated — it silently stops being freshness-checked too.
func renderArtifacts(
	catalogs map[string]map[string]message,
	langs []string,
) (map[string][]byte, error) {
	keysSrc, err := renderKeys(catalogs[canonicalLang])
	if err != nil {
		return nil, err
	}
	langsGoSrc, err := renderLangsGo(langs)
	if err != nil {
		return nil, err
	}
	artifacts := map[string][]byte{
		keysOutPath:    keysSrc,
		langsGoOutPath: langsGoSrc,
		langsTSOutPath: renderLangsTS(langs),
		catalogsTSPath: renderCatalogsTS(langs),
	}
	for lang, catalog := range catalogs {
		artifacts[tsOutDir+"/"+lang+".ts"] = renderTS(lang, catalog)
	}
	return artifacts, nil
}

// loadCatalogs reads every <name>.<lang>.json in dir into map[lang]map[key]message.
func loadCatalogs(dir string) (map[string]map[string]message, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read catalog dir: %w", err)
	}
	catalogs := map[string]map[string]message{}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".json") {
			continue
		}
		parts := strings.Split(name, ".")
		if len(parts) < 3 {
			return nil, fmt.Errorf("catalog %q: name must be <domain>.<lang>.json", name)
		}
		lang := parts[len(parts)-2]
		if !langTokenRe.MatchString(lang) {
			return nil, fmt.Errorf(
				"catalog %q: language token %q must be lowercase letters and digits "+
					"starting with a letter — it is emitted as the TS identifier "+
					"%sCatalog, so a region subtag or separator generates a catalog "+
					"that cannot parse",
				name, lang, lang)
		}

		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		parsed, err := parseCatalog(data)
		if err != nil {
			return nil, fmt.Errorf("catalog %q: %w", name, err)
		}
		if catalogs[lang] == nil {
			catalogs[lang] = map[string]message{}
		}
		for key, msg := range parsed {
			if _, dup := catalogs[lang][key]; dup {
				return nil, fmt.Errorf(
					"catalog %q: key %q already defined in another %s catalog",
					name,
					key,
					lang,
				)
			}
			catalogs[lang][key] = msg
		}
	}
	return catalogs, nil
}

// parseCatalog decodes one catalog file: values are either strings or
// {form: text} plural objects.
func parseCatalog(data []byte) (map[string]message, error) {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	out := map[string]message{}
	for key, rawMsg := range raw {
		var single string
		if err := json.Unmarshal(rawMsg, &single); err == nil {
			out[key] = message{single: single}
			continue
		}
		var forms map[string]string
		if err := json.Unmarshal(rawMsg, &forms); err != nil {
			return nil, fmt.Errorf(
				"key %q: value must be a string or an object of plural forms",
				key,
			)
		}
		out[key] = message{forms: forms}
	}
	return out, nil
}

// validateCatalogs returns every catalog-quality problem found (empty = clean).
// The language set is whatever loadCatalogs discovered — every OTHER
// declaration of it is generated from exactly this set, so there is nothing
// left to cross-check it against. plurals supplies the per-language CLDR
// categories validateMessage demands.
func validateCatalogs(catalogs map[string]map[string]message, plurals pluralForms) []string {
	canonical := catalogs[canonicalLang]
	if len(canonical) == 0 {
		return []string{fmt.Sprintf(
			"no %s catalog messages found — %s is the canonical catalog everything else "+
				"derives from (locale/messages.%s.json missing or empty)",
			canonicalLang, canonicalLang, canonicalLang)}
	}

	var problems []string
	langs := slices.Sorted(maps.Keys(catalogs))
	for _, lang := range langs {
		if len(catalogs[lang]) == 0 {
			problems = append(problems, fmt.Sprintf(
				"no %s catalog messages found — the scan is broken or the catalog is empty",
				lang))
		}
	}
	if len(problems) > 0 {
		return problems
	}

	for _, key := range slices.Sorted(maps.Keys(canonical)) {
		if !keyRe.MatchString(key) {
			problems = append(
				problems,
				fmt.Sprintf(
					"key %q: must be dot-separated snake_case with at least two segments",
					key,
				),
			)
		}
	}
	for _, lang := range langs {
		problems = append(problems, validateLang(lang, catalogs[lang], canonical, plurals)...)
	}
	return problems
}

// validateLang checks one language's catalog against the canonical key set.
func validateLang(
	lang string,
	catalog, canonical map[string]message,
	plurals pluralForms,
) []string {
	var problems []string
	for _, key := range slices.Sorted(maps.Keys(canonical)) {
		msg, ok := catalog[key]
		if !ok {
			problems = append(problems, fmt.Sprintf("catalog %s: missing key %q", lang, key))
			continue
		}
		problems = append(problems, validateMessage(lang, key, msg, plurals)...)
		if (msg.forms == nil) != (canonical[key].forms == nil) {
			problems = append(problems, fmt.Sprintf(
				"key %q: %s and %s disagree on plural vs plain (string vs object)",
				key, lang, canonicalLang))
		}
		if canonicalParams := canonical[key].params(); !slices.Equal(
			msg.params(),
			canonicalParams,
		) {
			problems = append(problems, fmt.Sprintf(
				"key %q: %s params %v differ from %s params %v",
				key, lang, msg.params(), canonicalLang, canonicalParams))
		}
	}
	for _, key := range slices.Sorted(maps.Keys(catalog)) {
		if _, ok := canonical[key]; !ok {
			problems = append(
				problems,
				fmt.Sprintf(
					"catalog %s: key %q missing from the canonical %s catalog",
					lang,
					key,
					canonicalLang,
				),
			)
		}
	}
	return problems
}

// validateMessage checks one message's shape: non-empty text, valid CLDR
// forms with "other" present, and lowercase-first {param} placeholders.
func validateMessage(lang, key string, msg message, plurals pluralForms) []string {
	var problems []string
	for _, text := range msg.texts() {
		for _, match := range braceTokenRe.FindAllStringSubmatch(text, -1) {
			if !paramRe.MatchString("{" + match[1] + "}") {
				problems = append(problems, fmt.Sprintf(
					"key %q (%s): placeholder {%s} must start with a lowercase letter",
					key, lang, match[1]))
			}
		}
	}
	if msg.forms == nil {
		if strings.TrimSpace(msg.single) == "" {
			problems = append(problems, fmt.Sprintf("key %q (%s): empty message", key, lang))
		}
		return problems
	}
	if _, ok := msg.forms["other"]; !ok {
		problems = append(
			problems,
			fmt.Sprintf("key %q (%s): plural object must define the \"other\" form", key, lang),
		)
	}
	// The renderer requires a numeric count for EVERY plural message and shows
	// the raw key when it is missing, so a plural that never prints the number
	// is unrenderable — and invisible to every other gate, because params()
	// then reports no params at all and the call-site check demands nothing.
	if !slices.Contains(msg.params(), "count") {
		problems = append(problems, fmt.Sprintf(
			"key %q (%s): plural object references no {count} placeholder — the "+
				"renderer needs a numeric count to pick a form and would show the "+
				"raw key instead; use a plain string if the number is not printed",
			key, lang))
	}
	// A language must declare every category its own rules can select.
	for _, form := range plurals[lang] {
		if _, ok := msg.forms[form]; !ok {
			problems = append(problems, fmt.Sprintf(
				"key %q (%s): plural object is missing the %q form — Intl.PluralRules"+
					"(%q) selects it, and the renderer would silently fall back to "+
					"the %q text",
				key, lang, form, lang, "other"))
		}
	}
	// Every form must carry the SAME placeholders. params() unions across
	// forms, so a single form dropping {count} leaves the union unchanged and
	// slips past both the en↔lang param comparison and the call-site gate —
	// the number then vanishes for exactly the counts that select that form.
	union := msg.params()
	for _, form := range slices.Sorted(maps.Keys(msg.forms)) {
		if !cldrForms[form] {
			problems = append(
				problems,
				fmt.Sprintf("key %q (%s): unknown plural form %q", key, lang, form),
			)
		}
		if strings.TrimSpace(msg.forms[form]) == "" {
			problems = append(problems, fmt.Sprintf("key %q (%s): empty %q form", key, lang, form))
		}
		if formParams := (message{single: msg.forms[form]}).params(); !slices.Equal(
			formParams,
			union,
		) {
			problems = append(problems, fmt.Sprintf(
				"key %q (%s): form %q references params %v but the message references "+
					"%v — every form must carry the same placeholders",
				key, lang, form, formParams, union))
		}
	}
	return problems
}

// renderKeys emits the msgkey source for the canonical catalog's key set.
func renderKeys(canonical map[string]message) ([]byte, error) {
	names := map[string]string{} // const name → key (collision detection)
	var b bytes.Buffer
	b.WriteString(genHeader + "\n\n")
	b.WriteString("// Package msgkey holds one typed constant per message in the translation\n")
	b.WriteString("// catalogs (locale/messages.<lang>.json — UI texts and error messages in\n")
	b.WriteString("// one namespace). Domain errors carry these keys instead of prose; the API\n")
	b.WriteString("// ships {key, params} and the FRONTEND renders the text.\n")
	b.WriteString("// Regenerate with `make i18n-gen` after editing a catalog.\n")
	b.WriteString("package msgkey\n\n")
	b.WriteString("// Key identifies one message in the translation catalogs.\n")
	b.WriteString("type Key string\n\n")
	b.WriteString("const (\n")
	for _, key := range slices.Sorted(maps.Keys(canonical)) {
		name := constName(key)
		if prev, dup := names[name]; dup {
			return nil, fmt.Errorf("keys %q and %q both map to const %s", prev, key, name)
		}
		names[name] = key
		fmt.Fprintf(&b, "\t%s Key = %q\n", name, key)
	}
	b.WriteString(")\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return src, nil
}

// renderTS emits one frontend catalog file — DATA ONLY. The public type
// surface (TranslationKey, TranslationCatalog) is declared in hand-written
// lang.ts, which derives the key union from the canonical catalog; every
// other language is annotated with TranslationCatalog, so vue-tsc re-checks
// key parity on the frontend side too. The canonical file imports nothing
// (lang.ts imports IT), the rest import only from lang.ts — never from a
// sibling catalog.
func renderTS(lang string, catalog map[string]message) []byte {
	var b strings.Builder
	fmt.Fprintf(&b,
		"// Code generated by gk i18n from locale/messages.%s.json; "+
			"DO NOT EDIT — edit the JSON and run make i18n-gen.\n\n", lang)
	if lang == canonicalLang {
		b.WriteString("export const " + lang + "Catalog = {\n")
	} else {
		b.WriteString("import type { TranslationCatalog } from '" + feLangModule + "';\n\n")
		b.WriteString("export const " + lang + "Catalog: TranslationCatalog = {\n")
	}
	for _, key := range slices.Sorted(maps.Keys(catalog)) {
		msg := catalog[key]
		if msg.forms == nil {
			fmt.Fprintf(&b, "    '%s': '%s',\n", tsEscape(key), tsEscape(msg.single))
			continue
		}
		fmt.Fprintf(&b, "    '%s': {\n", tsEscape(key))
		for _, form := range cldrOrder {
			text, ok := msg.forms[form]
			if !ok {
				continue
			}
			fmt.Fprintf(&b, "        %s: '%s',\n", form, tsEscape(text))
		}
		b.WriteString("    },\n")
	}
	if lang == canonicalLang {
		b.WriteString("} as const;\n")
	} else {
		b.WriteString("};\n")
	}
	return []byte(b.String())
}

// tsEscape makes a text safe inside a single-quoted TS string literal. Both
// line terminators are escaped: a raw CR (a translator pasting CRLF text)
// terminates the literal exactly like a raw LF does, and neither the catalog
// validation nor the freshness check can see it — the failure surfaces as an
// "Unterminated string literal" in a DO-NOT-EDIT file. U+2028/U+2029 need no
// escape (ES2019 made them legal in string literals).
func tsEscape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "'", `\'`)
	s = strings.ReplaceAll(s, "\r", `\r`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	return s
}

// constName maps "request.single_json_object_required" → "RequestSingleJSONObjectRequired".
func constName(key string) string {
	var b strings.Builder
	segments := strings.FieldsFunc(key, func(r rune) bool { return r == '.' || r == '_' })
	for _, seg := range segments {
		if up, ok := initialisms[seg]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(seg[:1]) + seg[1:])
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// Usage gates (run by `check`) — ported from the deleted
// app/infrastructure/i18n/zz_catalog_test.go so `go test` losing the package
// did not lose the invariants.
// ---------------------------------------------------------------------------

// checkUsage is the union deadness gate: every catalog key must be referenced
// either in Go production code (a msgkey.<Const> selector under app/ + cmd/,
// tests and the generated file excluded) or in frontend source (a quoted
// 'the.key' literal anywhere under assets/, the generated catalogs excluded).
// A key dead on BOTH sides is a text nobody can ever see.
func checkUsage(root string, canonical map[string]message, scan *productionScan) []string {
	if len(scan.usedNames) == 0 {
		return []string{"no msgkey usages found in Go production code — the scan is broken"}
	}
	feLiterals, scanned, err := frontendKeyLiterals(root)
	if err != nil {
		return []string{err.Error()}
	}
	if scanned == 0 {
		return []string{"no frontend source files scanned under assets/ — the scan is broken"}
	}

	var problems []string
	for _, key := range slices.Sorted(maps.Keys(canonical)) {
		if scan.usedNames[constName(key)] || feLiterals[key] {
			continue
		}
		problems = append(problems, fmt.Sprintf(
			"key %q is referenced neither by Go production code (msgkey.%s) nor by "+
				"frontend source — dead catalog entry", key, constName(key)))
	}
	return problems
}

// feKeyLiteralRe matches a quote-delimited token in catalog-key shape —
// 'user.created', "user.created", `user.created` — the only form a key
// reference takes in frontend source. Constraining the CONTENT to the key
// charset (rather than "anything between two quotes") is what makes the scan
// survive nesting: in :aria-label="t('nav.close_menu')" the outer pair holds
// no key and the inner one is still found.
var feKeyLiteralRe = regexp.MustCompile("['\"`]([a-z0-9._]+)['\"`]")

// frontendKeyLiterals collects the quoted key-shaped literals of every
// frontend source file under assets/ (.ts/.tsx/.vue/.js) into one set and
// reports how many files it saw. The generated catalog dir is skipped — it
// quotes every key, so scanning it would make the deadness gate blind. One
// pass answering each key with a set lookup replaces a per-key scan of the
// whole tree; a bare word in prose no longer counts as a reference.
func frontendKeyLiterals(root string) (map[string]bool, int, error) {
	literals := map[string]bool{}
	scanned := 0
	generated := filepath.Join(root, filepath.FromSlash(tsOutDir))
	err := filepath.WalkDir(filepath.Join(root, "assets"), func(
		path string, d fs.DirEntry, err error,
	) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path == generated {
				return fs.SkipDir
			}
			return nil
		}
		switch filepath.Ext(path) {
		case ".ts", ".tsx", ".vue", ".js":
		default:
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		scanned++
		for _, match := range feKeyLiteralRe.FindAllSubmatch(data, -1) {
			literals[string(match[1])] = true
		}
		return nil
	})
	if err != nil {
		return nil, 0, fmt.Errorf("walk assets: %w", err)
	}
	return literals, scanned, nil
}

// productionScan is what ONE pass over the production Go tree yields: the
// msgkey constants the code references (the Go half of the deadness gate) and
// every keyed call site (the params gate). Both gates used to walk and parse
// the whole app/ + cmd/ tree on their own.
type productionScan struct {
	usedNames map[string]bool
	sites     []keyedCallSite
}

// scanProductionGo parses every production Go file under app/ + cmd/ once
// (_test.go and the generated keys file excluded) and runs both gates'
// visitors over it. Files are prefiltered with an ImportsOnly parse: neither
// gate can see anything in a file that does not import msgkey, so only the
// handful that do pay for a full parse.
func scanProductionGo(root string) (*productionScan, error) {
	scan := &productionScan{usedNames: map[string]bool{}}
	fset := token.NewFileSet()
	prefilter := token.NewFileSet() // imports only — keeps the position-carrying fset clean
	for _, sub := range []string{"app", "cmd"} {
		err := filepath.WalkDir(filepath.Join(root, sub), func(
			path string, d fs.DirEntry, err error,
		) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") ||
				strings.HasSuffix(path, "keys.gen.go") {
				return nil
			}
			src, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			local, err := msgkeyImportName(prefilter, path, src)
			if err != nil || local == "" {
				return err
			}
			f, parseErr := parser.ParseFile(fset, path, src, 0)
			if parseErr != nil {
				return fmt.Errorf("parse %s: %w", path, parseErr)
			}
			if err := scan.collect(fset, f, local); err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return scan, nil
}

// msgkeyImportName returns the name msgkey is imported under in src, or "" when
// the file does not import it at all.
func msgkeyImportName(fset *token.FileSet, path string, src []byte) (string, error) {
	f, err := parser.ParseFile(fset, path, src, parser.ImportsOnly)
	if err != nil {
		return "", fmt.Errorf("parse imports of %s: %w", path, err)
	}
	for _, imp := range f.Imports {
		importPath, uerr := strconv.Unquote(imp.Path.Value)
		if uerr != nil {
			return "", fmt.Errorf("%s: malformed import path %s: %w", path, imp.Path.Value, uerr)
		}
		if importPath != msgkeyImportPath {
			continue
		}
		if imp.Name != nil {
			return imp.Name.Name, nil
		}
		return "msgkey", nil
	}
	return "", nil
}

// collect runs both gates' visitors over one parsed file; local is the name
// msgkey is imported under there.
func (s *productionScan) collect(fset *token.FileSet, f *ast.File, local string) error {
	var visitErr error
	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.SelectorExpr:
			if ident, isIdent := node.X.(*ast.Ident); isIdent && ident.Name == local {
				s.usedNames[node.Sel.Name] = true
			}
		case *ast.CompositeLit:
			site, err := keyedSite(fset, node, local)
			switch {
			case err != nil && visitErr == nil:
				visitErr = err
			case site != nil:
				s.sites = append(s.sites, *site)
			}
		}
		return true
	})
	return visitErr
}

// literalParamNames extracts the constant string keys of a `map[string]any{...}`
// literal. literal=false means the expression is not such a literal (a variable,
// a call, a non-string key) and the call site cannot be checked statically; an
// error means a key that will not unquote, i.e. malformed source.
func literalParamNames(expr ast.Expr) (names map[string]bool, literal bool, err error) {
	lit, isLit := expr.(*ast.CompositeLit)
	if !isLit {
		return nil, false, nil
	}
	if _, isMap := lit.Type.(*ast.MapType); !isMap {
		return nil, false, nil
	}
	names = map[string]bool{}
	for _, elt := range lit.Elts {
		kv, isKV := elt.(*ast.KeyValueExpr)
		if !isKV {
			return nil, false, nil
		}
		key, isStr := kv.Key.(*ast.BasicLit)
		if !isStr || key.Kind != token.STRING {
			return nil, false, nil
		}
		name, uerr := strconv.Unquote(key.Value)
		if uerr != nil {
			return nil, false, fmt.Errorf("malformed Params key %s: %w", key.Value, uerr)
		}
		names[name] = true
	}
	return names, true, nil
}

// keyedCallSite is one composite literal carrying `Key: msgkey.<Const>` —
// the shape every keyed error/config literal in production uses.
type keyedCallSite struct {
	pos       token.Position
	constName string
	params    map[string]bool
	checkable bool // false: Params is a non-literal expression
}

// keyedSite reads one composite literal as a keyed call site: a `Key:` field
// holding a msgkey selector, plus the statically known Params. nil means the
// literal is not one (no such Key field).
func keyedSite(
	fset *token.FileSet,
	lit *ast.CompositeLit,
	local string,
) (*keyedCallSite, error) {
	site := keyedCallSite{params: map[string]bool{}, checkable: true}
	for _, elt := range lit.Elts {
		kv, isKV := elt.(*ast.KeyValueExpr)
		if !isKV {
			continue
		}
		field, isIdent := kv.Key.(*ast.Ident)
		if !isIdent {
			continue
		}
		switch field.Name {
		case "Key":
			sel, isSel := kv.Value.(*ast.SelectorExpr)
			if !isSel {
				continue
			}
			if ident, ok := sel.X.(*ast.Ident); ok && ident.Name == local {
				site.constName = sel.Sel.Name
				site.pos = fset.Position(lit.Pos())
			}
		case "Params":
			names, literal, err := literalParamNames(kv.Value)
			if err != nil {
				return nil, err
			}
			if !literal {
				site.checkable = false
				continue
			}
			site.params = names
		}
	}
	if site.constName == "" {
		return nil, nil
	}
	return &site, nil
}

// checkCallSiteParams closes the loop the catalog validation cannot: the
// catalog knows its placeholders, but a Go call site that forgets (or
// misnames) a Params entry ships a message the frontend cannot interpolate.
// Every statically checkable `Key: msgkey.X` literal must cover every {param}
// (incl. count, which drives plural selection) of X's canonical message.
// Params passed as a non-literal expression are skipped — they cannot be
// verified statically.
func checkCallSiteParams(canonical map[string]message, scan *productionScan) []string {
	keysByConst := map[string]string{}
	for key := range canonical {
		keysByConst[constName(key)] = key
	}

	var problems []string
	checked := 0
	for _, site := range scan.sites {
		if !site.checkable {
			continue
		}
		key, known := keysByConst[site.constName]
		if !known {
			// A selector like msgkey.Key (the type) — not a message constant.
			continue
		}
		checked++
		for _, name := range canonical[key].params() {
			if !site.params[name] {
				problems = append(problems, fmt.Sprintf(
					"%s: msgkey.%s (%q) is missing template param %q — "+
						"the frontend cannot fill the placeholder",
					site.pos, site.constName, key, name))
			}
		}
	}
	if checked == 0 {
		problems = append(problems,
			"no checkable msgkey call sites found in Go production code — the gate sees nothing")
	}
	return problems
}

// feCallSiteRe matches a t() call with a literal key and, optionally, a flat
// literal params object: t('bulk.selected', { count, total }). RE2 has no
// lookbehind, so the leading non-word guard is what keeps `format(` and a
// `.t(` method call out. A negated class spans newlines, so a params object
// broken across lines still matches.
var feCallSiteRe = regexp.MustCompile(
	"(?:^|[^\\w.$])t\\(\\s*['\"`]([a-z0-9._]+)['\"`]\\s*(?:,\\s*\\{([^{}]*)\\}\\s*)?\\)")

// feParamNameRe: one entry of a literal params object, in `name:` or shorthand
// `name` form.
var feParamNameRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// literalFEParams reads a flat `{ a, b: expr }` params body into a name set.
// ok=false means an entry is not a plain `name` / `name:` pair — a spread, a
// computed key, or a value carrying a comma — and the call site is then
// SKIPPED rather than guessed at, exactly like a non-literal Go Params.
func literalFEParams(body string) (map[string]bool, bool) {
	names := map[string]bool{}
	for _, part := range strings.Split(body, ",") {
		entry := strings.TrimSpace(part)
		if entry == "" {
			continue
		}
		if i := strings.IndexByte(entry, ':'); i >= 0 {
			entry = strings.TrimSpace(entry[:i])
		}
		if !feParamNameRe.MatchString(entry) {
			return nil, false
		}
		names[entry] = true
	}
	return names, true
}

// checkFrontendCallSiteParams is checkCallSiteParams' frontend half. The Go
// scan only walks app/ + cmd/, but most placeholder-bearing keys are rendered
// ONLY from assets/, where TranslationParams is a flat Record<string, …> that
// cannot tell one key's params from another's — so vue-tsc happily accepts
// t('bulk.selected', { count }) for a message that also needs {total}, and
// interpolate leaves the literal "{total}" on screen. Every t() call with a
// statically readable params object must cover its key's placeholders.
func checkFrontendCallSiteParams(root string, canonical map[string]message) []string {
	var problems []string
	checked := 0
	generated := filepath.Join(root, filepath.FromSlash(tsOutDir))
	err := filepath.WalkDir(filepath.Join(root, "assets"), func(
		path string, d fs.DirEntry, err error,
	) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path == generated {
				return fs.SkipDir
			}
			return nil
		}
		switch filepath.Ext(path) {
		case ".ts", ".tsx", ".vue", ".js":
		default:
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			rel = path
		}
		for _, match := range feCallSiteRe.FindAllSubmatch(data, -1) {
			key := string(match[1])
			msg, known := canonical[key]
			if !known {
				// Not a catalog key (a route name, a CSS token) — the deadness
				// gate owns unknown-looking literals, not this one.
				continue
			}
			supplied, literal := literalFEParams(string(match[2]))
			if !literal {
				continue
			}
			checked++
			for _, name := range msg.params() {
				if !supplied[name] {
					problems = append(problems, fmt.Sprintf(
						"%s: t(%q) is missing template param %q — "+
							"the placeholder would render literally",
						rel, key, name))
				}
			}
		}
		return nil
	})
	if err != nil {
		return []string{fmt.Sprintf("walk assets: %v", err)}
	}
	if checked == 0 {
		return append(problems,
			"no checkable t() call sites found under assets/ — the gate sees nothing")
	}
	return problems
}

// langConstName maps a catalog's language token to its Go constant name —
// LangCS, LangEN. Language tags are lowercase by langTokenRe, and Go style
// uppercases short codes wholesale (the same shape the hand-written constants
// had before they became generated, so no call site moved).
func langConstName(lang string) string { return "Lang" + strings.ToUpper(lang) }

// renderLangsGo emits the backend's declaration of the language set: one Lang
// constant per discovered catalog, the canonical default, and the two lookups
// every consumer goes through. Nothing here is language-specific knowledge —
// it is the catalog filenames transcribed into Go, which is precisely why it
// must not be hand-maintained.
func renderLangsGo(langs []string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(genHeader + "\n\n")
	b.WriteString("package shared\n\n")
	b.WriteString("// The UI languages the app ships catalogs for, discovered from the\n")
	b.WriteString("// locale/messages.<lang>.json filenames. Adding a language is\n")
	b.WriteString("// a catalog file plus `make i18n-gen` — never an edit here.\n")
	b.WriteString("const (\n")
	for _, lang := range langs {
		fmt.Fprintf(&b, "\t%s Lang = %q\n", langConstName(lang), lang)
	}
	b.WriteString("\n")
	b.WriteString("\t// DefaultLang is the canonical language: the fallback when a request\n")
	b.WriteString("\t// carries no usable language signal, and the one served at bare URLs.\n")
	b.WriteString("\t// Mirrors CANONICAL_LANG on the frontend.\n")
	fmt.Fprintf(&b, "\tDefaultLang = %s\n", langConstName(canonicalLang))
	b.WriteString(")\n\n")

	b.WriteString("// SupportedLangs lists every language the app ships catalogs for.\n")
	b.WriteString("func SupportedLangs() []Lang { return []Lang{")
	for i, lang := range langs {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(langConstName(lang))
	}
	b.WriteString("} }\n\n")

	b.WriteString("// ParseLang validates a raw value (header, URL segment, DB column) into a\n")
	b.WriteString("// Lang. Matching is exact — normalization (e.g. \"cs-CZ\", \"EN\") is the\n")
	b.WriteString("// caller's job; HTTP Accept-Language negotiation lives in the\n")
	b.WriteString("// LangMiddleware.\n")
	b.WriteString("func ParseLang(raw string) (Lang, bool) {\n")
	b.WriteString("\tswitch Lang(raw) {\n")
	for _, lang := range langs {
		name := langConstName(lang)
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %s, true\n", name, name)
	}
	b.WriteString("\t}\n\n\treturn \"\", false\n}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}

	return src, nil
}

// renderLangsTS emits the frontend's declaration of the same set. The Lang
// union is declared HERE rather than in hand-written lang.ts so the two cannot
// drift: lang.ts re-exports it, and every consumer keeps importing from
// lang.ts as before.
func renderLangsTS(langs []string) []byte {
	var b strings.Builder
	b.WriteString(tsGenHeader)
	b.WriteString("// The UI languages the app ships catalogs for, discovered from the\n")
	b.WriteString("// locale/messages.<lang>.json filenames. Mirrors shared.SupportedLangs.\n")
	b.WriteString("export const SUPPORTED_LANGS = [")
	for i, lang := range langs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "'%s'", lang)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type Lang = (typeof SUPPORTED_LANGS)[number];\n\n")
	b.WriteString("// CANONICAL_LANG lives at bare URLs; every other language carries a\n")
	b.WriteString("// /<lang> path prefix. Mirrors shared.DefaultLang.\n")
	fmt.Fprintf(&b, "export const CANONICAL_LANG: Lang = '%s';\n", canonicalLang)

	return []byte(b.String())
}

// renderCatalogsTS emits the language→catalog record the renderer looks up in.
// The `satisfies` is the frontend half of catalog validation — a malformed
// plural or a key missing from a non-canonical catalog fails vue-tsc here —
// and it only covers every language because the record is generated from the
// same discovered set as the Lang union it is checked against.
func renderCatalogsTS(langs []string) []byte {
	var b strings.Builder
	b.WriteString(tsGenHeader)
	for _, lang := range langs {
		fmt.Fprintf(&b, "import { %sCatalog } from '%s/%s';\n", lang, feCatalogModule, lang)
	}
	fmt.Fprintf(&b, "import type { Lang, TranslationCatalog } from '%s';\n\n", feLangModule)
	b.WriteString("export const catalogs = {\n")
	for _, lang := range langs {
		fmt.Fprintf(&b, "    %s: %sCatalog,\n", lang, lang)
	}
	b.WriteString("} satisfies Record<Lang, TranslationCatalog>;\n\n")
	b.WriteString("// The canonical catalog under a language-neutral name: it is complete by\n")
	b.WriteString("// construction, so the TranslationKey union derives from it and membership\n")
	b.WriteString("// in it IS the definition of a known key. Exported from here so no\n")
	b.WriteString("// hand-written module has to name the canonical language.\n")
	fmt.Fprintf(&b, "export const canonicalCatalog = %sCatalog;\n", canonicalLang)

	return []byte(b.String())
}

// cldrPluralJS asks Node for the plural categories of each language named on
// the command line. resolvedOptions().locale is compared back against the
// request because Intl FALLS BACK for a tag its ICU does not know — without
// the comparison an unknown language would quietly inherit the default
// locale's categories, which is worse than having no entry at all.
const cldrPluralJS = `const out = {};
for (const lang of process.argv.slice(1)) {
    const opts = new Intl.PluralRules(lang).resolvedOptions();
    if (opts.locale.toLowerCase().split('-')[0] !== lang) {
        process.stderr.write(lang + ' -> ' + opts.locale);
        process.exit(2);
    }
    out[lang] = opts.pluralCategories.slice().sort();
}
process.stdout.write(JSON.stringify(out));`

// cldrPluralForms reads the categories out of Node's Intl.PluralRules — the
// same implementation the renderer selects forms with at runtime, so the gate
// cannot demand a form the frontend would never pick (or miss one it does).
// One spawn per run, on both `generate` and `check`: `make lint` already
// requires Node for eslint, vue-tsc and knip, and a cached table would ratify
// its own errors (see the pluralForms doc).
func cldrPluralForms(langs []string) (pluralForms, error) {
	cmd := exec.Command("node", append([]string{"-e", cldrPluralJS}, langs...)...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr

	if err := cmd.Run(); err != nil {
		var exit *exec.ExitError
		if errors.As(err, &exit) && exit.ExitCode() == 2 {
			return nil, fmt.Errorf(
				"language %s is unknown to this Node's ICU, so its plural categories "+
					"cannot be derived — check the catalog filename, or use a Node build "+
					"with full ICU", stderr.String())
		}

		return nil, fmt.Errorf(
			"reading the CLDR plural categories for %v needs node on PATH — the gate "+
				"holds every catalog to the forms Intl.PluralRules can select, and it "+
				"asks Node rather than caching them so a wrong table cannot ratify "+
				"itself (`make lint` already needs node for eslint and vue-tsc): %w: %s",
			langs, err, stderr.String())
	}

	var forms pluralForms
	if err := json.Unmarshal(stdout.Bytes(), &forms); err != nil {
		return nil, fmt.Errorf("parse node plural output %q: %w", stdout.String(), err)
	}
	// Every language has at least "other", so an empty list means the bridge
	// broke — and an empty list is exactly what makes the per-language form
	// check silently demand nothing, so it must never be accepted quietly.
	for _, lang := range langs {
		if len(forms[lang]) == 0 {
			return nil, fmt.Errorf(
				"node reported no plural categories for %q — the CLDR bridge is "+
					"broken and the per-language form check would demand nothing", lang)
		}
	}

	return forms, nil
}
