// Code generated by tsgen; DO NOT EDIT.

import type { Role } from '@/app/Auth/enums/roles';
import { arrayOf, isRecord, isString } from '@/app-ui/Fetch/guards';
import { isRole } from '@/app/Auth/enums/roles';

export type AuthUser = {
    id: string;
    nickname: string;
    email: string;
    role: Role;
    permissions: string[];
    lang: string;
};

export const isAuthUser = (v: unknown): v is AuthUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['nickname'])
    && isString(v['email'])
    && isRole(v['role'])
    && arrayOf(isString)(v['permissions'])
    && isString(v['lang']);
