// Code generated by tsgen; DO NOT EDIT.

import { arrayOf, isRecord, isString } from '@/app-ui/Fetch/guards';

export type AuthUser = {
    id: string;
    nickname: string;
    email: string;
    role: string;
    permissions: string[];
};

export const isAuthUser = (v: unknown): v is AuthUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['nickname'])
    && isString(v['email'])
    && isString(v['role'])
    && arrayOf(isString)(v['permissions']);
