// Code generated by tsgen; DO NOT EDIT.

import type { AuthUser } from '@/app-ui/Auth/types/AuthUser';
import { isNumber, isRecord, isString } from '@/app-ui/Fetch/guards';
import { isAuthUser } from '@/app-ui/Auth/types/AuthUser';

export type LoginResponse = {
    access_token: string;
    access_expiration: number;
    user: AuthUser;
};

export const isLoginResponse = (v: unknown): v is LoginResponse =>
    isRecord(v)
    && isString(v['access_token'])
    && isNumber(v['access_expiration'])
    && isAuthUser(v['user']);
