// Code generated by tsgen; DO NOT EDIT.

export type PlatformUser = {
    id: string;
    nickname: string;
    email: string;
    role: string;
    active: boolean;
    tenant_id: string;
    tenant_name: string;
    last_login_at: string | null;
};
