// Code generated by tsgen; DO NOT EDIT.

export type PlatformBulkActiveUsersRequest = {
    ids: string[];
    all_filtered: boolean;
    tenant: string;
    nickname: string;
    email: string;
    role: string;
    active: string;
    set_active: boolean;
};
