// Code generated by tsgen; DO NOT EDIT.

import { isBoolean, isNumber, isRecord, isString } from '@/app-ui/Fetch/guards';

export type PlatformTenant = {
    id: string;
    name: string;
    plan: string;
    user_count: number;
    is_default: boolean;
};

export const isPlatformTenant = (v: unknown): v is PlatformTenant =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['name'])
    && isString(v['plan'])
    && isNumber(v['user_count'])
    && isBoolean(v['is_default']);
