// Code generated by tsgen; DO NOT EDIT.

import type { Role } from '@/app/Auth/enums/roles';
import { isBoolean, isRecord, isString, nullable } from '@/app-ui/Fetch/guards';
import { isRole } from '@/app/Auth/enums/roles';

export type PlatformUser = {
    id: string;
    nickname: string;
    email: string;
    role: Role;
    active: boolean;
    tenant_id: string;
    tenant_name: string;
    last_login_at: string | null;
};

export const isPlatformUser = (v: unknown): v is PlatformUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['nickname'])
    && isString(v['email'])
    && isRole(v['role'])
    && isBoolean(v['active'])
    && isString(v['tenant_id'])
    && isString(v['tenant_name'])
    && nullable(isString)(v['last_login_at']);
