// Code generated by tsgen; DO NOT EDIT.

import type { PlatformUser } from '@/app/Platform/types/PlatformUser';
import { arrayOf, isNumber, isRecord } from '@/app-ui/Fetch/guards';
import { isPlatformUser } from '@/app/Platform/types/PlatformUser';

export type PlatformUserListResponse = {
    items: PlatformUser[];
    total: number;
};

export const isPlatformUserListResponse = (v: unknown): v is PlatformUserListResponse =>
    isRecord(v)
    && arrayOf(isPlatformUser)(v['items'])
    && isNumber(v['total']);
