// Code generated by tsgen; DO NOT EDIT.

import type { PlatformTenant } from '@/app/Platform/types/PlatformTenant';
import { arrayOf, isNumber, isRecord } from '@/app-ui/Fetch/guards';
import { isPlatformTenant } from '@/app/Platform/types/PlatformTenant';

export type PlatformTenantListResponse = {
    items: PlatformTenant[];
    total: number;
};

export const isPlatformTenantListResponse = (v: unknown): v is PlatformTenantListResponse =>
    isRecord(v)
    && arrayOf(isPlatformTenant)(v['items'])
    && isNumber(v['total']);
