// Code generated by tsgen; DO NOT EDIT.

import { isNumber, isRecord } from '@/app-ui/Fetch/guards';

export type PlatformStats = {
    tenant_count: number;
    user_count: number;
};

export const isPlatformStats = (v: unknown): v is PlatformStats =>
    isRecord(v)
    && isNumber(v['tenant_count'])
    && isNumber(v['user_count']);
