// Package tsgen (the `gk tsgen` subcommand) generates TypeScript type
// definitions from annotated Go structs, so the frontend request/response
// types can never silently drift from the Go DTOs that actually cross the
// HTTP wire (audit finding F-082).
//
// A Go struct opts in with a directive comment naming its exact output path and
// the TS type to emit (the author places each type precisely where the frontend
// needs it):
//
//	//gkts:assets/app-ui/Auth/types/LoginResponse.ts LoginResponse
//	type loginResponse struct { ... }
//
// Alongside each type a RUNTIME GUARD (export const isLoginResponse = ...) is
// emitted BY DEFAULT — the fetch layer requires it via `validate:` so a 2xx
// body is checked against the generated contract at runtime. Request-only DTOs
// (the FE sends them, never receives them) append `noguard` to skip the guard:
//
//	//gkts:assets/app/Admin/types/UserFormData.ts UserFormData noguard
//
// Path FIRST is deliberate: a lowercase path right after the colon makes this a
// genuine gofmt/golines directive, so the formatter leaves it verbatim. A
// //gkts:<Name> form (uppercase after the colon) is NOT a recognized directive,
// so golines would rewrite it to "// gkts:<Name>" and silently break parsing.
//
// tsgen maps the struct's json-tagged fields to TS and writes (or, in `check`
// mode, verifies) the target file. It lives in the gokick-gk dev-tooling
// module (own go.mod) so the project linters — which forbid stdout and direct
// file writes — do not apply to a tool whose whole job is exactly that.
//
// Type mapping is deliberately SMALL and fail-loud: it maps only the Go types the
// DTOs actually use and ERRORS on anything else, rather than emitting `any` and
// re-opening the very parity gap it exists to close. Extend mapType when a new
// field type appears; never let it guess.
//
// Usage:
//
//	gk tsgen generate   # write the TS files (make ts-gen)
//	gk tsgen check      # verify on-disk files match; exit 1 on drift (CI gate)
package tsgen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

const genHeader = "// Code generated by tsgen; DO NOT EDIT."

// directive is a parsed //gkts:<path> <Name>[ noguard] annotation.
type directive struct {
	tsName  string // TypeScript type name to emit
	noguard bool   // suppress the runtime guard (request-only DTOs — FE sends, never receives)
	tsPath  string // output path, repo-relative (e.g. assets/app-ui/Auth/types/LoginResponse.ts)
}

// dtoField is one rendered field: its JSON key, TS type, optionality, and (if the
// type is another generated type) the import that type needs.
type dtoField struct {
	name     string // JSON key (= TS property name)
	tsType   string // rendered TS type
	optional bool   // json ",omitempty" → name?: type
	dep      string // Go type name of a referenced generated type, or ""
	shape    fieldShape
}

// fieldShape is the structured view of a field's type that guard emission
// composes from (the rendered tsType string is for the type declaration only).
type fieldShape struct {
	kind     string // "string" | "number" | "boolean" | "named"
	array    bool   // []T
	nullable bool   // *T → T | null
}

// dto is one annotated struct resolved to its TS shape.
type dto struct {
	goName string
	dir    directive
	fields []dtoField
}

// Run is the `gk tsgen` entrypoint; args are the words after "tsgen".
func Run(args []string) {
	mode := "generate"
	if len(args) > 0 {
		mode = args[0]
	}
	root := repoRoot()

	dtos, err := collect(filepath.Join(root, "app"))
	if err != nil {
		fatal("collect: %v", err)
	}
	if len(dtos) == 0 {
		fatal("no //gkts: directives found under app/ — nothing to generate")
	}

	byGo, err := indexDTOs(dtos)
	if err != nil {
		fatal("%v", err)
	}

	files, err := render(dtos, byGo)
	if err != nil {
		fatal("render: %v", err)
	}

	switch mode {
	case "generate":
		writeFiles(root, files)
	case "check":
		checkFiles(root, files)
	default:
		fatal("unknown mode %q (want: generate | check)", mode)
	}
}

// indexDTOs indexes the DTOs by Go type name so a nested field (e.g. userDTO)
// resolves to the TS name + import path of the type it maps to.
func indexDTOs(dtos []dto) (map[string]directive, error) {
	byGo := make(map[string]directive, len(dtos))
	for _, d := range dtos {
		if prev, ok := byGo[d.goName]; ok && prev != d.dir {
			return nil, fmt.Errorf(
				"Go type %q carries two conflicting //gkts: directives", d.goName)
		}
		byGo[d.goName] = d.dir
	}
	return byGo, nil
}

// collect parses every non-test .go file under dir and returns the annotated DTOs.
func collect(dir string) ([]dto, error) {
	var dtos []dto
	fset := token.NewFileSet()
	err := filepath.WalkDir(dir, func(path string, e os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if e.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, perr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if perr != nil {
			return fmt.Errorf("parse %s: %w", path, perr)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				// The directive sits on the type's own doc, or (for a single-spec
				// `type X struct`) on the GenDecl's doc.
				dir, ok, derr := parseDirective(ts.Doc, gd.Doc)
				if derr != nil {
					return fmt.Errorf("%s: %w", path, derr)
				}
				if !ok {
					continue
				}
				fields, ferr := structFields(st)
				if ferr != nil {
					return fmt.Errorf("%s: type %s: %w", path, ts.Name.Name, ferr)
				}
				dtos = append(dtos, dto{goName: ts.Name.Name, dir: dir, fields: fields})
			}
		}
		return nil
	})
	return dtos, err
}

// parseDirective looks for a //gkts:<path> <Name>[ noguard] line in the given
// comment groups. Path first (lowercase after the colon) keeps it a gofmt/golines
// directive so the formatter never rewrites it — see the package doc.
func parseDirective(groups ...*ast.CommentGroup) (directive, bool, error) {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			rest, ok := strings.CutPrefix(line, "gkts:")
			if !ok {
				continue
			}
			f := strings.Fields(rest)
			switch {
			case len(f) == 2:
				return directive{tsName: f[1], tsPath: f[0]}, true, nil
			// Guards are emitted BY DEFAULT (a response type without one would
			// silently skip runtime validation); `noguard` opts a request-only
			// DTO out so knip never sees an uncalled guard.
			case len(f) == 3 && f[2] == "noguard":
				return directive{tsName: f[1], tsPath: f[0], noguard: true}, true, nil
			default:
				return directive{}, false, fmt.Errorf(
					"malformed directive %q (want: //gkts:<path> <TSName>[ noguard])", c.Text)
			}
		}
	}
	return directive{}, false, nil
}

// structFields resolves each json-serialized field to its TS shape. It errors on
// any Go field type mapType does not understand — fail loud, never emit `any`.
func structFields(st *ast.StructType) ([]dtoField, error) {
	var out []dtoField
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			return nil, fmt.Errorf("embedded fields are not supported")
		}
		name, omitempty, skip := jsonName(f)
		if skip {
			continue
		}
		for _, n := range f.Names {
			// encoding/json serializes ONLY exported fields, tag or no tag — so an
			// unexported field never reaches the wire. Emitting it would make the TS
			// assert a property that never arrives; skip it exactly as json does.
			if !n.IsExported() {
				continue
			}
			key := name
			if key == "" {
				key = n.Name // encoding/json falls back to the field name
			}
			tsType, dep, sh, err := mapType(f.Type)
			if err != nil {
				return nil, fmt.Errorf("field %s: %w", n.Name, err)
			}
			out = append(
				out,
				dtoField{name: key, tsType: tsType, optional: omitempty, dep: dep, shape: sh},
			)
		}
	}
	return out, nil
}

// jsonName reads the json tag: returns the key, whether it is ,omitempty, and
// whether the field is skipped (json:"-").
func jsonName(f *ast.Field) (name string, omitempty, skip bool) {
	if f.Tag == nil {
		return "", false, false
	}
	tag := reflect.StructTag(strings.Trim(f.Tag.Value, "`"))
	j, ok := tag.Lookup("json")
	if !ok {
		return "", false, false
	}
	parts := strings.Split(j, ",")
	if parts[0] == "-" {
		return "", false, true
	}
	for _, p := range parts[1:] {
		if p == "omitempty" {
			omitempty = true
		}
	}
	return parts[0], omitempty, false
}

// mapType turns a Go type expression into a TS type. dep is the Go type name of a
// referenced generated type (for imports), or "". It errors on anything outside
// the small set the DTOs use — extend it deliberately, don't guess.
func mapType(expr ast.Expr) (tsType, dep string, sh fieldShape, err error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", "", fieldShape{kind: "string"}, nil
		case "bool":
			return "boolean", "", fieldShape{kind: "boolean"}, nil
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64":
			return "number", "", fieldShape{kind: "number"}, nil
		default:
			// A named local type — valid only if it is itself a generated DTO.
			// Resolution to its TS name happens in render (which has the registry);
			// here we just carry the Go name as the dependency.
			return t.Name, t.Name, fieldShape{kind: "named"}, nil
		}
	case *ast.ArrayType:
		// []T -> T[] (never T[]|null). A NIL Go slice marshals to JSON `null`, which
		// would break `T[]` at runtime — so DTO slice fields MUST be non-nil-
		// initialized by the handler (the gokick convention: e.g. permissions comes
		// from registry.ForRole, which starts `[]string{}`). This tool cannot enforce
		// that at compile time; keeping T[] matches the convention and the FE's use
		// (no null-guard on arrays) rather than pessimizing every slice to |null.
		elem, dep, esh, err := mapType(t.Elt)
		if err != nil {
			return "", "", fieldShape{}, err
		}
		if esh.array || esh.nullable {
			return "", "", fieldShape{}, fmt.Errorf(
				"nested array/pointer element (%s) is not guard-composable — flatten the DTO",
				elem)
		}
		esh.array = true
		return elem + "[]", dep, esh, nil
	case *ast.StarExpr:
		elem, dep, esh, err := mapType(t.X)
		if err != nil {
			return "", "", fieldShape{}, err
		}
		if esh.nullable {
			return "", "", fieldShape{}, fmt.Errorf(
				"pointer-to-pointer (%s) is not guard-composable — flatten the DTO", elem)
		}
		esh.nullable = true
		return elem + " | null", dep, esh, nil
	default:
		return "", "", fieldShape{}, fmt.Errorf(
			"unmapped Go type %T — extend tsgen.mapType (do not emit `any`)", expr)
	}
}

// render groups DTOs by output file and produces the file contents. It resolves
// each nested dependency to the TS name + import path of the type it maps to.
func render(dtos []dto, byGo map[string]directive) (map[string]string, error) {
	// Group the DTOs targeting each file, in the order encountered.
	byFile := map[string][]dto{}
	var order []string
	for _, d := range dtos {
		if _, seen := byFile[d.dir.tsPath]; !seen {
			order = append(order, d.dir.tsPath)
		}
		byFile[d.dir.tsPath] = append(byFile[d.dir.tsPath], d)
	}

	out := make(map[string]string, len(order))
	for _, path := range order {
		group, err := dedupe(path, byFile[path])
		if err != nil {
			return nil, err
		}

		// A file may host several types; a name defined here needs no import.
		localNames := map[string]bool{}
		for _, d := range group {
			localNames[d.dir.tsName] = true
		}

		imports := map[string]string{}      // tsName -> import specifier (type imports)
		valueImports := map[string]string{} // guard name -> import specifier
		helpers := map[string]bool{}        // guard primitives used from Fetch/guards
		var body strings.Builder
		for i, d := range group {
			if i > 0 {
				body.WriteString("\n")
			}
			if err := renderType(&body, d, byGo, localNames, imports); err != nil {
				return nil, fmt.Errorf("%s: %w", path, err)
			}
			if d.dir.noguard {
				continue
			}
			body.WriteString("\n")
			if err := renderGuard(&body, d, byGo, localNames, valueImports, helpers); err != nil {
				return nil, fmt.Errorf("%s: %w", path, err)
			}
		}

		var sb strings.Builder
		sb.WriteString(genHeader + "\n")
		if len(imports) > 0 || len(helpers) > 0 || len(valueImports) > 0 {
			sb.WriteString("\n")
			names := make([]string, 0, len(imports))
			for n := range imports {
				names = append(names, n)
			}
			sort.Strings(names)
			for _, n := range names {
				fmt.Fprintf(&sb, "import type { %s } from '%s';\n", n, imports[n])
			}
			if len(helpers) > 0 {
				hs := make([]string, 0, len(helpers))
				for h := range helpers {
					hs = append(hs, h)
				}
				sort.Strings(hs)
				fmt.Fprintf(&sb, "import { %s } from '@/app-ui/Fetch/guards';\n",
					strings.Join(hs, ", "))
			}
			gnames := make([]string, 0, len(valueImports))
			for n := range valueImports {
				gnames = append(gnames, n)
			}
			sort.Strings(gnames)
			for _, n := range gnames {
				fmt.Fprintf(&sb, "import { %s } from '%s';\n", n, valueImports[n])
			}
		}
		sb.WriteString("\n")
		sb.WriteString(body.String())
		out[path] = sb.String()
	}
	return out, nil
}

// dedupe collapses DTOs that map to the same TS name in one file. Several Go
// request DTOs legitimately share a TS type (e.g. create/update/platform user all
// mirror UserFormData); an identical shape is emitted once. Two DTOs claiming the
// same TS name with DIFFERENT fields is a real conflict — fail loud, don't pick one.
func dedupe(path string, group []dto) ([]dto, error) {
	seen := map[string]dto{}
	var uniq []dto
	for _, d := range group {
		if prev, ok := seen[d.dir.tsName]; ok {
			if !fieldsEqual(prev.fields, d.fields) {
				return nil, fmt.Errorf(
					"%s: TS type %q is defined by both %q and %q with different fields — "+
						"reconcile the Go DTOs or give them distinct //gkts: names",
					path, d.dir.tsName, prev.goName, d.goName)
			}
			if prev.dir.noguard != d.dir.noguard {
				return nil, fmt.Errorf(
					"%s: TS type %q is noguard on %q but not on %q — the duplicate "+
						"directives must agree",
					path, d.dir.tsName, prev.goName, d.goName)
			}
			continue // identical duplicate — one definition suffices
		}
		seen[d.dir.tsName] = d
		uniq = append(uniq, d)
	}
	return uniq, nil
}

func fieldsEqual(a, b []dtoField) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// renderType writes one `export type` block and records any imports its fields need.
func renderType(
	sb *strings.Builder,
	d dto,
	byGo map[string]directive,
	localNames map[string]bool,
	imports map[string]string,
) error {
	fmt.Fprintf(sb, "export type %s = {\n", d.dir.tsName)
	for _, f := range d.fields {
		tsType := f.tsType
		if f.dep != "" {
			ref, ok := byGo[f.dep]
			if !ok {
				return fmt.Errorf(
					"field %q references Go type %q, which has no //gkts: directive — annotate it or the reference cannot be typed",
					f.name,
					f.dep,
				)
			}
			// Substitute the dependency's TS name for its Go name in the rendered type
			// (handles `userDTO`, `userDTO[]`, `userDTO | null`).
			tsType = strings.Replace(tsType, f.dep, ref.tsName, 1)
			if !localNames[ref.tsName] {
				imports[ref.tsName] = importSpec(ref.tsPath)
			}
		}
		opt := ""
		if f.optional {
			opt = "?"
		}
		fmt.Fprintf(sb, "    %s%s: %s;\n", f.name, opt, tsType)
	}
	sb.WriteString("};\n")
	return nil
}

// renderGuard writes the runtime guard for one DTO — a composition of the
// primitives in assets/app-ui/Fetch/guards.ts mirroring the type shape, so a
// parsed JSON body can be validated against the generated contract. Extra
// (undeclared) properties are deliberately tolerated: the backend may add
// fields without breaking older readers; missing or mistyped DECLARED fields
// fail.
func renderGuard(
	sb *strings.Builder,
	d dto,
	byGo map[string]directive,
	localNames map[string]bool,
	valueImports map[string]string,
	helpers map[string]bool,
) error {
	helpers["isRecord"] = true
	fmt.Fprintf(sb, "export const is%s = (v: unknown): v is %s =>\n", d.dir.tsName, d.dir.tsName)
	sb.WriteString("    isRecord(v)")
	for _, f := range d.fields {
		var base string
		switch f.shape.kind {
		case "string":
			base = "isString"
		case "number":
			base = "isNumber"
		case "boolean":
			base = "isBoolean"
		case "named":
			ref, ok := byGo[f.dep]
			if !ok {
				return fmt.Errorf(
					"guard field %q references Go type %q with no //gkts: directive", f.name, f.dep)
			}
			if ref.noguard {
				return fmt.Errorf(
					"guard field %q references %s, which is marked noguard — a validated type "+
						"cannot nest an unvalidatable one", f.name, ref.tsName)
			}
			base = "is" + ref.tsName
			if !localNames[ref.tsName] {
				valueImports[base] = importSpec(ref.tsPath)
			}
		default:
			return fmt.Errorf("guard field %q has unknown shape kind %q", f.name, f.shape.kind)
		}
		if f.shape.kind != "named" {
			helpers[base] = true
		}
		expr := base
		if f.shape.array {
			helpers["arrayOf"] = true
			expr = "arrayOf(" + expr + ")"
		}
		if f.shape.nullable {
			helpers["nullable"] = true
			expr = "nullable(" + expr + ")"
		}
		if f.optional {
			helpers["optional"] = true
			expr = "optional(" + expr + ")"
		}
		fmt.Fprintf(sb, "\n    && %s(v['%s'])", expr, f.name)
	}
	sb.WriteString(";\n")
	return nil
}

// importSpec turns a repo-relative TS path into the '@/...' alias the frontend uses.
func importSpec(tsPath string) string {
	p := strings.TrimSuffix(tsPath, ".ts")
	p = strings.TrimPrefix(p, "assets/")
	return "@/" + p
}

func writeFiles(root string, files map[string]string) {
	for rel, content := range files {
		abs := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			fatal("mkdir %s: %v", filepath.Dir(abs), err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			fatal("write %s: %v", rel, err)
		}
		fmt.Printf("tsgen: wrote %s\n", rel)
	}
	for _, rel := range orphans(root, files) {
		if err := os.Remove(filepath.Join(root, rel)); err != nil {
			fatal("prune orphan %s: %v", rel, err)
		}
		fmt.Printf("tsgen: pruned orphan %s\n", rel)
	}
	fmt.Printf("tsgen: %d file(s) generated\n", len(files))
}

// checkFiles verifies each generated file matches disk; exits 1 on any drift. This
// is the CI gate: if a Go DTO changed without re-running `make ts-gen`, it fails.
func checkFiles(root string, files map[string]string) {
	var drift []string
	for rel, want := range files {
		got, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			drift = append(drift, rel+" (missing — run make ts-gen)")
			continue
		}
		if string(got) != want {
			drift = append(drift, rel+" (out of date — run make ts-gen)")
		}
	}
	for _, rel := range orphans(root, files) {
		drift = append(
			drift,
			rel+" (orphan — no //gkts directive produces it; run make ts-gen to prune)",
		)
	}
	if len(drift) > 0 {
		sort.Strings(drift)
		fmt.Fprintln(os.Stderr, "tsgen: generated TypeScript is out of date:")
		for _, d := range drift {
			fmt.Fprintln(os.Stderr, "  - "+d)
		}
		os.Exit(1)
	}
	fmt.Printf("tsgen: %d file(s) up to date\n", len(files))
}

// orphans returns generated files still on disk (identified by the DO-NOT-EDIT
// header) that the CURRENT directive set no longer produces — a //gkts directive
// was deleted or its path repointed, leaving a stale, now-authorless TS type the
// frontend keeps importing. generate prunes them; check reports them as drift.
func orphans(root string, current map[string]string) []string {
	var out []string
	err := filepath.WalkDir(
		filepath.Join(root, "assets"),
		func(path string, e os.DirEntry, err error) error {
			if err != nil || e.IsDir() || !strings.HasSuffix(path, ".ts") {
				return nil
			}
			b, rerr := os.ReadFile(path)
			if rerr != nil {
				return rerr
			}
			if !strings.HasPrefix(string(b), genHeader) {
				return nil
			}
			rel := filepath.ToSlash(mustRel(root, path))
			if _, live := current[rel]; !live {
				out = append(out, rel)
			}
			return nil
		},
	)
	if err != nil {
		fatal("scan for orphans: %v", err)
	}
	sort.Strings(out)
	return out
}

func mustRel(base, path string) string {
	rel, err := filepath.Rel(base, path)
	if err != nil {
		fatal("rel %s: %v", path, err)
	}
	return rel
}

// repoRoot resolves the gokick module root by walking up from the working
// directory (gk runs from tools/gk).
func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal("getwd: %v", err)
	}
	for {
		mod := filepath.Join(dir, "go.mod")
		if b, err := os.ReadFile(mod); err == nil &&
			strings.Contains(string(b), "module gokick\n") {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal("could not find gokick go.mod above %s", dir)
		}
		dir = parent
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "tsgen: "+format+"\n", args...)
	os.Exit(1)
}
