// Code generated by gk i18n from locale/; DO NOT EDIT — add a catalog and run make i18n-gen.

import { csCatalog } from '@/app-ui/I18n/catalog/cs';
import { enCatalog } from '@/app-ui/I18n/catalog/en';
import type { Lang, TranslationCatalog } from '@/app-ui/I18n/lang';

export const catalogs = {
    cs: csCatalog,
    en: enCatalog,
} satisfies Record<Lang, TranslationCatalog>;

// The canonical catalog under a language-neutral name: it is complete by
// construction, so the TranslationKey union derives from it and membership
// in it IS the definition of a known key. Exported from here so no
// hand-written module has to name the canonical language.
export const canonicalCatalog = enCatalog;
