// Code generated by gk i18n from locale/; DO NOT EDIT — add a catalog and run make i18n-gen.

// The UI languages the app ships catalogs for, discovered from the
// locale/messages.<lang>.json filenames. Mirrors shared.SupportedLangs.
export const SUPPORTED_LANGS = ['cs', 'en'] as const;

export type Lang = (typeof SUPPORTED_LANGS)[number];

// CANONICAL_LANG lives at bare URLs; every other language carries a
// /<lang> path prefix. Mirrors shared.DefaultLang.
export const CANONICAL_LANG: Lang = 'en';
