// Code generated by tsgen; DO NOT EDIT.

export const Role = {
    SuperAdmin: 'superadmin',
    Admin: 'admin',
    User: 'user',
} as const;

export type Role = typeof Role[keyof typeof Role];

export const isRole = (v: unknown): v is Role =>
    v === Role.SuperAdmin
    || v === Role.Admin
    || v === Role.User;
