// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di_container

import (
	"log/slog"
	"myapp/app"
	"myapp/app/console"
	"myapp/app/env"
	"myapp/app/handler"
	"myapp/app/server"
)

// Injectors from container_provider.go:

func CreateApplication(logger *slog.Logger) (*app.Application, error) {
	config, err := env.LoadConfig()
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler()
	serverServer := server.NewServer(config, logger, healthHandler)
	serveCommand := console.NewServeCommand(serverServer)
	rootCommand := console.NewRootCommand(serveCommand)
	application := app.NewApplication(rootCommand)
	return application, nil
}
