// Code generated by tsgen; DO NOT EDIT.

import { isNumber, isRecord } from '@/app-ui/Fetch/guards';

export type BulkResult = {
    affected: number;
};

export const isBulkResult = (v: unknown): v is BulkResult =>
    isRecord(v)
    && isNumber(v['affected']);
