// Code generated by gk i18n; DO NOT EDIT.

package shared

// The UI languages the app ships catalogs for, discovered from the
// locale/messages.<lang>.json filenames. Adding a language is
// a catalog file plus `make i18n-gen` — never an edit here.
const (
	LangCS Lang = "cs"
	LangEN Lang = "en"

	// DefaultLang is the canonical language: the fallback when a request
	// carries no usable language signal, and the one served at bare URLs.
	// Mirrors CANONICAL_LANG on the frontend.
	DefaultLang = LangEN
)

// SupportedLangs lists every language the app ships catalogs for.
func SupportedLangs() []Lang { return []Lang{LangCS, LangEN} }

// ParseLang validates a raw value (header, URL segment, DB column) into a
// Lang. Matching is exact — normalization (e.g. "cs-CZ", "EN") is the
// caller's job; HTTP Accept-Language negotiation lives in the
// LangMiddleware.
func ParseLang(raw string) (Lang, bool) {
	switch Lang(raw) {
	case LangCS:
		return LangCS, true
	case LangEN:
		return LangEN, true
	}

	return "", false
}
