// Code generated by tsgen; DO NOT EDIT.

import { arrayOf, isRecord, isString } from '@/app-ui/Fetch/guards';

export type Owner = {
    name: string;
    peers: Owner[];
};

export const isOwner = (v: unknown): v is Owner =>
    isRecord(v)
    && isString(v['name'])
    && arrayOf(isOwner)(v['peers']);
