// Code generated by tsgen; DO NOT EDIT.

import type { Owner } from '@/types/Owner';
import { arrayOf, isBoolean, isNumber, isRecord, isString, nullable } from '@/app-ui/Fetch/guards';
import { isOwner } from '@/types/Owner';

export type Widget = {
    id: string;
    count: number;
    ratio: number;
    active: boolean;
    tags: string[];
    note: string | null;
    owner: Owner;
    Plain: string;
};

export const isWidget = (v: unknown): v is Widget =>
    isRecord(v)
    && isString(v['id'])
    && isNumber(v['count'])
    && isNumber(v['ratio'])
    && isBoolean(v['active'])
    && arrayOf(isString)(v['tags'])
    && nullable(isString)(v['note'])
    && isOwner(v['owner'])
    && isString(v['Plain']);
