// Code generated by tsgen; DO NOT EDIT.

import type { AdminUser } from '@/app/Admin/types/AdminUser';
import { arrayOf, isNumber, isRecord } from '@/app-ui/Fetch/guards';
import { isAdminUser } from '@/app/Admin/types/AdminUser';

export type AdminUserListResponse = {
    items: AdminUser[];
    total: number;
};

export const isAdminUserListResponse = (v: unknown): v is AdminUserListResponse =>
    isRecord(v)
    && arrayOf(isAdminUser)(v['items'])
    && isNumber(v['total']);
