// Code generated by tsgen; DO NOT EDIT.

import type { Role } from '@/app/Auth/enums/roles';
import { isBoolean, isRecord, isString } from '@/app-ui/Fetch/guards';
import { isRole } from '@/app/Auth/enums/roles';

export type AdminUser = {
    id: string;
    nickname: string;
    email: string;
    role: Role;
    active: boolean;
};

export const isAdminUser = (v: unknown): v is AdminUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['nickname'])
    && isString(v['email'])
    && isRole(v['role'])
    && isBoolean(v['active']);
