// Code generated by tsgen; DO NOT EDIT.

import { isBoolean, isRecord, isString } from '@/app-ui/Fetch/guards';

export type AdminUser = {
    id: string;
    nickname: string;
    email: string;
    role: string;
    active: boolean;
};

export const isAdminUser = (v: unknown): v is AdminUser =>
    isRecord(v)
    && isString(v['id'])
    && isString(v['nickname'])
    && isString(v['email'])
    && isString(v['role'])
    && isBoolean(v['active']);
