// Code generated by tsgen; DO NOT EDIT.

export type BulkDeleteUsersRequest = {
    ids: string[];
    all_filtered: boolean;
    nickname: string;
    email: string;
    role: string;
    active: string;
};
