// Code generated by tsgen; DO NOT EDIT.

import type { Role } from '@/app/Auth/enums/roles';

export type UserFormData = {
    nickname: string;
    password: string;
    email: string;
    role: Role;
};
